In [1]:
#import statements

import numpy as np
import pandas as pd
from glob import glob
from datetime import date, timedelta
import datetime
import math

In [2]:
#list out data files

fils = sorted(glob('Dataset/*.csv'))
fils

['Dataset/raw_data01.csv',
 'Dataset/raw_data02.csv',
 'Dataset/raw_data03.csv',
 'Dataset/raw_data04.csv',
 'Dataset/raw_data05.csv',
 'Dataset/raw_data06.csv',
 'Dataset/raw_data07.csv',
 'Dataset/raw_data08.csv',
 'Dataset/raw_data09.csv',
 'Dataset/raw_data10.csv',
 'Dataset/raw_data11.csv',
 'Dataset/raw_data12.csv',
 'Dataset/raw_data13.csv',
 'Dataset/raw_data14.csv',
 'Dataset/raw_data15.csv',
 'Dataset/raw_data16.csv',
 'Dataset/raw_data17.csv',
 'Dataset/raw_data18.csv',
 'Dataset/raw_data19.csv']

In [3]:
#frame dataframe from data files

case_time = pd.read_csv('Dataset/Extd/case_time_series.csv')
state_wise = pd.read_csv('Dataset/Extd/state_wise_daily.csv')
states = pd.read_csv('Dataset/Extd/states.csv')
df = pd.concat((pd.read_csv(file).assign(filename = file)
          for file in fils),ignore_index = True)
df

/home/hoozeeloogaan/Programs/anaconda3/lib/python3.7/site-packages/ipykernel_launcher.py:7: FutureWarning: Sorting because non-concatenation axis is not aligned. A future version
of pandas will change to not sort by default.

To accept the future behavior, pass 'sort=False'.

To retain the current behavior and silence the warning, pass 'sort=True'.

  import sys

,Age Bracket,Backup Notes,Contracted from which Patient (Suspected),Current Status,Date Announced,Detected City,Detected District,Detected State,Entry_ID,Estimated Onset Date,...,Patient Number,Source_1,Source_2,Source_3,State Patient Number,State code,Status Change Date,Type of transmission,filename,months
0,20,Student from Wuhan,NaN,Recovered,30/01/2020,Thrissur,Thrissur,Kerala,NaN,NaN,...,1.0,https://twitter.com/vijayanpinarayi/status/122...,https://weather.com/en-IN/india/news/news/2020...,NaN,KL-TS-P1,KL,14/02/2020,Imported,Dataset/raw_data01.csv,NaN
1,NaN,Student from Wuhan,NaN,Recovered,02/02/2020,Alappuzha,Alappuzha,Kerala,NaN,NaN,...,2.0,https://www.indiatoday.in/india/story/kerala-r...,https://weather.com/en-IN/india/news/news/2020...,NaN,KL-AL-P1,KL,14/02/2020,Imported,Dataset/raw_data01.csv,NaN
2,NaN,Student from Wuhan,NaN,Recovered,03/02/2020,Kasaragod,Kasaragod,Kerala,NaN,NaN,...,3.0,https://www.indiatoday.in/india/story/kerala-n...,https://twitter.com/ANI/status/122422148580539...,https://weather.com/en-IN/india/news/news/2020...,KL-KS-P1,KL,14/02/2020,Imported,Dataset/raw_data01.csv,NaN
3,45,Travel history to Italy and Austria,NaN,Recovered,02/03/2020,East Delhi (Mayur Vihar),East Delhi,Delhi,NaN,NaN,...,4.0,https://www.indiatoday.in/india/story/not-a-ja...,https://economictimes.indiatimes.com/news/poli...,NaN,DL-P1,DL,15/03/2020,Imported,Dataset/raw_data01.csv,NaN
4,24,"Travel history to Dubai, Singapore contact",NaN,Recovered,02/03/2020,Hyderabad,Hyderabad,Telangana,NaN,NaN,...,5.0,https://www.deccanherald.com/national/south/qu...,https://www.indiatoday.in/india/story/coronavi...,https://www.thehindu.com/news/national/coronav...,TS-P1,TG,02/03/2020,Imported,Dataset/raw_data01.csv,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
427584,NaN,NaN,NaN,Recovered,28/11/2020,NaN,Leh,Ladakh,398941.0,NaN,...,NaN,http://covid.ladakh.gov.in/#dataInsights,NaN,NaN,NaN,LA,NaN,NaN,Dataset/raw_data19.csv,NaN
427585,NaN,NaN,NaN,Recovered,28/11/2020,NaN,Kargil,Ladakh,398942.0,NaN,...,NaN,http://covid.ladakh.gov.in/#dataInsights,NaN,NaN,NaN,LA,NaN,NaN,Dataset/raw_data19.csv,NaN
427586,NaN,NaN,NaN,Deceased,28/11/2020,NaN,Leh,Ladakh,398943.0,NaN,...,NaN,http://covid.ladakh.gov.in/#dataInsights,NaN,NaN,NaN,LA,NaN,NaN,Dataset/raw_data19.csv,NaN
427587,NaN,NaN,NaN,Recovered,28/11/2020,NaN,Ahmedabad,Gujarat,398944.0,NaN,...,NaN,https://gujcovid19.gujarat.gov.in/,NaN,NaN,NaN,GJ,NaN,NaN,Dataset/raw_data19.csv,NaN
427588,NaN,NaN,NaN,Recovered,28/11/2020,NaN,Valsad,Gujarat,398945.0,NaN,...,NaN,https://gujcovid19.gujarat.gov.in/,NaN,NaN,NaN,GJ,NaN,NaN,Dataset/raw_data19.csv,NaN

In [4]:
#extract needed features from the data and add primary key

df = df[["Date Announced","Current Status","Detected District","Detected State","Age Bracket"]]

In [5]:
#removing all rows with age value NaN

data = df.dropna()
data_n = df.dropna(subset=['Date Announced','Current Status','Detected District'])
data = data.rename(columns = { 'Date Announced':'Date_Announced','Current Status':'Current_Status','Detected District':'Detected_District','Detected State':'Detected_State','Age Bracket':'Age_Bracket' })
Patient_id = list(range(len(data)))
data['Patient_id'] = Patient_id
data = data[data['Current_Status'] != 'Migrated_Other']
data['Detected_District'] = data['Detected_District'].str.lower()
data['Detected_State'] = data['Detected_State'].str.lower()

In [ ]:
#add age bitmap to the dataframe

newlist = [0]*len(data)
data['Age_0_15'] = newlist
data['Age_15_30'] = newlist
data['Age_30_45'] = newlist
data['Age_45_60'] = newlist
data['Age_60'] = newlist

for i in data.index:
    age = (data.loc[i,['Age_Bracket']])
    x = age.to_string()
    if len(x) >= 18:
        print(x)
        age = x.split('-')[0][-2:]
        age = math.ceil(float(age))
    age = int(age)
    if age > 0 and age <= 15:
        data.loc[i,['Age_0_15']] = 1
    elif age > 15 and age <= 30:
        data.loc[i,['Age_15_30']] = 1
    elif age > 30 and age <= 45:
        data.loc[i,['Age_30_45']] = 1
    elif age > 45 and age <= 60:
        data.loc[i,['Age_45_60']] = 1
    else:
        data.loc[i,['Age_60']] = 1
        
data

In [7]:
#district wise segregation

state_wise_filter = data[data['Detected_State'] == 'karnataka']
state_wise_filter

,Date_Announced,Current_Status,Detected_District,Detected_State,Age_Bracket,Patient_id
41,09/03/2020,Recovered,bengaluru urban,karnataka,46,33
50,10/03/2020,Recovered,bengaluru urban,karnataka,40,36
51,10/03/2020,Recovered,bengaluru urban,karnataka,47,37
52,10/03/2020,Recovered,bengaluru urban,karnataka,13,38
73,12/03/2020,Recovered,bengaluru urban,karnataka,26,49
...,...,...,...,...,...,...
299041,05/09/2020,Deceased,bengaluru urban,karnataka,65,113881
299042,05/09/2020,Deceased,hassan,karnataka,60,113882
299043,05/09/2020,Deceased,hassan,karnataka,66,113883
299044,05/09/2020,Deceased,ramanagara,karnataka,52,113884
299045,05/09/2020,Deceased,mysuru,karnataka,82,113885

In [8]:
district_list = state_wise_filter.Detected_District.unique()
(district_list)

district_data = dict()
for districts in district_list:
    district_data.update({districts:0})
district_data

{'bengaluru urban': 0,
 'kalaburagi': 0,
 'kodagu': 0,
 'chikkaballapura': 0,
 'mysuru': 0,
 'dharwad': 0,
 'uttara kannada': 0,
 'other state': 0,
 'udupi': 0,
 'chitradurga': 0,
 'dakshina kannada': 0,
 'tumakuru': 0,
 'davanagere': 0,
 'ballari': 0,
 'bidar': 0,
 'bagalkote': 0,
 'belagavi': 0,
 'bengaluru rural': 0,
 'gadag': 0,
 'mandya': 0,
 'vijayapura': 0,
 'haveri': 0,
 'shivamogga': 0,
 'yadgir': 0,
 'hassan': 0,
 'kolar': 0,
 'raichur': 0,
 'koppal': 0,
 'chikkamagaluru': 0,
 'ramanagara': 0,
 'chamarajanagara': 0}

In [9]:
#calander like dataframe

sdate = date(2020, 1, 1)
edate = date(2020, 12, 31)

delta = edate - sdate
dates = []

for i in range(delta.days + 1):
    day = sdate + timedelta(days=i)
    dates.append(day.strftime('%d/%m/%Y'))

In [10]:
#segregate dataset into recovered/deceased/hospitalized

recovered_data = data[data['Current_Status'] == 'Recovered']
deceased_data = data[data['Current_Status'] == 'Deceased']
hospitalized_data = data[data['Current_Status'] == 'Hospitalized']

In [11]:
#district-wise calender dataframe

for district in district_data:
    cal_dat = pd.DataFrame(columns=['Date_Announced','Total_Infections','Total_Recoveries','Total_Deceased','District','State'])
    cal_dat['Date_Announced'] = dates
    cal_dat.set_index('Date_Announced',inplace=True)
    
    buff_list = pd.DataFrame(hospitalized_data.loc[data['Detected_District']==district])
    grouped =  (buff_list.groupby('Date_Announced').groups)
    for i,j in grouped.items():
        grouped[i] = len(list(j))    

    for i in cal_dat.index:
        for j,k in grouped.items():
            if i == j:
                x = (cal_dat.loc[i,['Total_Infections']])
                if np.isnan(x['Total_Infections']):
                    cal_dat.loc[i,['Total_Infections']] = k
                else:
                    cal_dat.loc[i,['Total_Infections']] = x['Total_Infections'] + k
        cal_dat.loc[i,['District']] = district
        cal_dat.loc[i,['State']] = 'karnataka'
        
    
    buff_list = pd.DataFrame(recovered_data.loc[data['Detected_District']==district])
    grouped =  (buff_list.groupby('Date_Announced').groups)
    for i,j in grouped.items():
        grouped[i] = len(list(j))    

    for i in cal_dat.index:
        for j,k in grouped.items():
            if i == j:
                x = (cal_dat.loc[i,['Total_Recoveries']])
                if np.isnan(x['Total_Recoveries']):
                    cal_dat.loc[i,['Total_Recoveries']] = k
                else:
                    cal_dat.loc[i,['Total_Recoveries']] = x['Total_Recoveries'] + k
        
    
    buff_list = pd.DataFrame(deceased_data.loc[data['Detected_District']==district])
    grouped =  (buff_list.groupby('Date_Announced').groups)
    for i,j in grouped.items():
        grouped[i] = len(list(j))    

    for i in cal_dat.index:
        for j,k in grouped.items():
            if i == j:
                x = (cal_dat.loc[i,['Total_Deceased']])
                if np.isnan(x['Total_Deceased']):
                    cal_dat.loc[i,['Total_Deceased']] = k
                else:
                    cal_dat.loc[i,['Total_Deceased']] = x['Total_Deceased'] + k
        
    cal_dat['Total_Recoveries'] = cal_dat['Total_Recoveries'].replace(np.nan, 'DNA')
    cal_dat['Total_Deceased'] = cal_dat['Total_Deceased'].replace(np.nan, 'DNA') 
    cal_dat['Total_Infections'] = cal_dat['Total_Infections'].replace(np.nan, 'DNA') 
    district_data[district] = cal_dat

In [12]:
#specific o/p

pd.set_option('display.max_rows',466)
district_data['bidar']

,Total_Infections,Total_Recoveries,Total_Deceased,District,State
Date_Announced,,,,,
01/01/2020,DNA,DNA,DNA,bidar,karnataka
02/01/2020,DNA,DNA,DNA,bidar,karnataka
03/01/2020,DNA,DNA,DNA,bidar,karnataka
04/01/2020,DNA,DNA,DNA,bidar,karnataka
05/01/2020,DNA,DNA,DNA,bidar,karnataka
06/01/2020,DNA,DNA,DNA,bidar,karnataka
07/01/2020,DNA,DNA,DNA,bidar,karnataka
08/01/2020,DNA,DNA,DNA,bidar,karnataka
09/01/2020,DNA,DNA,DNA,bidar,karnataka
10/01/2020,DNA,DNA,DNA,bidar,karnataka
11/01/2020,DNA,DNA,DNA,bidar,karnataka
12/01/2020,DNA,DNA,DNA,bidar,karnataka
13/01/2020,DNA,DNA,DNA,bidar,karnataka
14/01/2020,DNA,DNA,DNA,bidar,karnataka
15/01/2020,DNA,DNA,DNA,bidar,karnataka
16/01/2020,DNA,DNA,DNA,bidar,karnataka
17/01/2020,DNA,DNA,DNA,bidar,karnataka
18/01/2020,DNA,DNA,DNA,bidar,karnataka
19/01/2020,DNA,DNA,DNA,bidar,karnataka
20/01/2020,DNA,DNA,DNA,bidar,karnataka
21/01/2020,DNA,DNA,DNA,bidar,karnataka
22/01/2020,DNA,DNA,DNA,bidar,karnataka
23/01/2020,DNA,DNA,DNA,bidar,karnataka
24/01/2020,DNA,DNA,DNA,bidar,karnataka
25/01/2020,DNA,DNA,DNA,bidar,karnataka
26/01/2020,DNA,DNA,DNA,bidar,karnataka
27/01/2020,DNA,DNA,DNA,bidar,karnataka
28/01/2020,DNA,DNA,DNA,bidar,karnataka
29/01/2020,DNA,DNA,DNA,bidar,karnataka
30/01/2020,DNA,DNA,DNA,bidar,karnataka
31/01/2020,DNA,DNA,DNA,bidar,karnataka
01/02/2020,DNA,DNA,DNA,bidar,karnataka
02/02/2020,DNA,DNA,DNA,bidar,karnataka
03/02/2020,DNA,DNA,DNA,bidar,karnataka
04/02/2020,DNA,DNA,DNA,bidar,karnataka
05/02/2020,DNA,DNA,DNA,bidar,karnataka
06/02/2020,DNA,DNA,DNA,bidar,karnataka
07/02/2020,DNA,DNA,DNA,bidar,karnataka
08/02/2020,DNA,DNA,DNA,bidar,karnataka
09/02/2020,DNA,DNA,DNA,bidar,karnataka
10/02/2020,DNA,DNA,DNA,bidar,karnataka
11/02/2020,DNA,DNA,DNA,bidar,karnataka
12/02/2020,DNA,DNA,DNA,bidar,karnataka
13/02/2020,DNA,DNA,DNA,bidar,karnataka
14/02/2020,DNA,DNA,DNA,bidar,karnataka
15/02/2020,DNA,DNA,DNA,bidar,karnataka
16/02/2020,DNA,DNA,DNA,bidar,karnataka
17/02/2020,DNA,DNA,DNA,bidar,karnataka
18/02/2020,DNA,DNA,DNA,bidar,karnataka
19/02/2020,DNA,DNA,DNA,bidar,karnataka
20/02/2020,DNA,DNA,DNA,bidar,karnataka
21/02/2020,DNA,DNA,DNA,bidar,karnataka
22/02/2020,DNA,DNA,DNA,bidar,karnataka
23/02/2020,DNA,DNA,DNA,bidar,karnataka
24/02/2020,DNA,DNA,DNA,bidar,karnataka
25/02/2020,DNA,DNA,DNA,bidar,karnataka
26/02/2020,DNA,DNA,DNA,bidar,karnataka
27/02/2020,DNA,DNA,DNA,bidar,karnataka
28/02/2020,DNA,DNA,DNA,bidar,karnataka
29/02/2020,DNA,DNA,DNA,bidar,karnataka
01/03/2020,DNA,DNA,DNA,bidar,karnataka
02/03/2020,DNA,DNA,DNA,bidar,karnataka
03/03/2020,DNA,DNA,DNA,bidar,karnataka
04/03/2020,DNA,DNA,DNA,bidar,karnataka
05/03/2020,DNA,DNA,DNA,bidar,karnataka
06/03/2020,DNA,DNA,DNA,bidar,karnataka
07/03/2020,DNA,DNA,DNA,bidar,karnataka
08/03/2020,DNA,DNA,DNA,bidar,karnataka
09/03/2020,DNA,DNA,DNA,bidar,karnataka
10/03/2020,DNA,DNA,DNA,bidar,karnataka
11/03/2020,DNA,DNA,DNA,bidar,karnataka
12/03/2020,DNA,DNA,DNA,bidar,karnataka
13/03/2020,DNA,DNA,DNA,bidar,karnataka
14/03/2020,DNA,DNA,DNA,bidar,karnataka
15/03/2020,DNA,DNA,DNA,bidar,karnataka
16/03/2020,DNA,DNA,DNA,bidar,karnataka
17/03/2020,DNA,DNA,DNA,bidar,karnataka
18/03/2020,DNA,DNA,DNA,bidar,karnataka
19/03/2020,DNA,DNA,DNA,bidar,karnataka
20/03/2020,DNA,DNA,DNA,bidar,karnataka
21/03/2020,DNA,DNA,DNA,bidar,karnataka
22/03/2020,DNA,DNA,DNA,bidar,karnataka
23/03/2020,DNA,DNA,DNA,bidar,karnataka
24/03/2020,DNA,DNA,DNA,bidar,karnataka
25/03/2020,DNA,DNA,DNA,bidar,karnataka
26/03/2020,DNA,DNA,DNA,bidar,karnataka
27/03/2020,DNA,DNA,DNA,bidar,karnataka
28/03/2020,DNA,DNA,DNA,bidar,karnataka
29/03/2020,DNA,DNA,DNA,bidar,karnataka
30/03/2020,DNA,DNA,DNA,bidar,karnataka
31/03/2020,DNA,DNA,DNA,bidar,karnataka
01/04/2020,DNA,DNA,DNA,bidar,karnataka
02/04/2020,9,DNA,DNA,bidar,karnataka
03/04/2020,DNA,DNA,DNA,bidar,karnataka
04/04/2020,DNA,DNA,DNA,bidar,karnataka
05/04/2020,DNA,DNA,DNA,bidar,karnataka
06/04/2020,DNA,DNA,DNA,bidar,karnataka
07/04/2020,DNA,DNA,DNA,bidar,karnataka
08/04/2020,DNA,DNA,DNA,bidar,karnataka
09/04/2020,DNA,DNA,DNA,bidar,karnataka
10/04/2020,DNA,DNA,DNA,bidar,karnataka
11/04/2020,1,DNA,DNA,bidar,karnataka
12/04/2020,DNA,DNA,DNA,bidar,karnataka
13/04/2020,2,DNA,DNA,bidar,karnataka
14/04/2020,DNA,DNA,DNA,bidar,karnataka
15/04/2020,DNA,DNA,DNA,bidar,karnataka
16/04/2020,DNA,DNA,DNA,bidar,karnataka
17/04/2020,1,DNA,DNA,bidar,karnataka
18/04/2020,DNA,DNA,DNA,bidar,karnataka
19/04/2020,DNA,DNA,DNA,bidar,karnataka
20/04/2020,1,DNA,DNA,bidar,karnataka
21/04/2020,DNA,DNA,DNA,bidar,karnataka
22/04/2020,DNA,DNA,DNA,bidar,karnataka
23/04/2020,DNA,DNA,DNA,bidar,karnataka
24/04/2020,DNA,DNA,DNA,bidar,karnataka
25/04/2020,DNA,DNA,DNA,bidar,karnataka
26/04/2020,DNA,DNA,DNA,bidar,karnataka
27/04/2020,DNA,DNA,DNA,bidar,karnataka
28/04/2020,DNA,DNA,DNA,bidar,karnataka
29/04/2020,DNA,DNA,DNA,bidar,karnataka
30/04/2020,DNA,DNA,DNA,bidar,karnataka
01/05/2020,DNA,DNA,DNA,bidar,karnataka
02/05/2020,1,DNA,1,bidar,karnataka
03/05/2020,DNA,DNA,DNA,bidar,karnataka
04/05/2020,7,DNA,DNA,bidar,karnataka
05/05/2020,DNA,DNA,DNA,bidar,karnataka
06/05/2020,DNA,DNA,DNA,bidar,karnataka
07/05/2020,DNA,DNA,DNA,bidar,karnataka
08/05/2020,DNA,DNA,DNA,bidar,karnataka
09/05/2020,3,DNA,DNA,bidar,karnataka
10/05/2020,DNA,DNA,DNA,bidar,karnataka
11/05/2020,2,DNA,DNA,bidar,karnataka
12/05/2020,2,DNA,DNA,bidar,karnataka
13/05/2020,11,DNA,DNA,bidar,karnataka
14/05/2020,7,DNA,DNA,bidar,karnataka
15/05/2020,7,DNA,1,bidar,karnataka
16/05/2020,DNA,DNA,DNA,bidar,karnataka
17/05/2020,DNA,DNA,DNA,bidar,karnataka
18/05/2020,1,DNA,DNA,bidar,karnataka
19/05/2020,1,DNA,DNA,bidar,karnataka
20/05/2020,10,DNA,DNA,bidar,karnataka
21/05/2020,DNA,DNA,DNA,bidar,karnataka
22/05/2020,7,DNA,DNA,bidar,karnataka
23/05/2020,3,DNA,DNA,bidar,karnataka
24/05/2020,6,DNA,DNA,bidar,karnataka
25/05/2020,1,DNA,DNA,bidar,karnataka
26/05/2020,10,DNA,DNA,bidar,karnataka
27/05/2020,13,DNA,DNA,bidar,karnataka
28/05/2020,12,DNA,DNA,bidar,karnataka
29/05/2020,DNA,DNA,DNA,bidar,karnataka
30/05/2020,10,DNA,DNA,bidar,karnataka
31/05/2020,33,DNA,1,bidar,karnataka
01/06/2020,2,DNA,DNA,bidar,karnataka
02/06/2020,10,DNA,DNA,bidar,karnataka
03/06/2020,DNA,DNA,DNA,bidar,karnataka
04/06/2020,DNA,DNA,DNA,bidar,karnataka
05/06/2020,39,DNA,DNA,bidar,karnataka
06/06/2020,1,DNA,1,bidar,karnataka
07/06/2020,7,DNA,DNA,bidar,karnataka
08/06/2020,48,DNA,DNA,bidar,karnataka
09/06/2020,9,DNA,DNA,bidar,karnataka
10/06/2020,5,DNA,DNA,bidar,karnataka
11/06/2020,14,DNA,DNA,bidar,karnataka
12/06/2020,10,DNA,DNA,bidar,karnataka
13/06/2020,42,DNA,DNA,bidar,karnataka
14/06/2020,20,DNA,DNA,bidar,karnataka
15/06/2020,11,DNA,DNA,bidar,karnataka
16/06/2020,2,DNA,1,bidar,karnataka
17/06/2020,12,DNA,1,bidar,karnataka
18/06/2020,6,DNA,1,bidar,karnataka
19/06/2020,10,DNA,2,bidar,karnataka
20/06/2020,73,DNA,2,bidar,karnataka
21/06/2020,13,DNA,2,bidar,karnataka
22/06/2020,5,DNA,DNA,bidar,karnataka
23/06/2020,22,DNA,DNA,bidar,karnataka
24/06/2020,5,DNA,DNA,bidar,karnataka
25/06/2020,8,DNA,DNA,bidar,karnataka
26/06/2020,1,DNA,1,bidar,karnataka
27/06/2020,17,DNA,3,bidar,karnataka
28/06/2020,7,DNA,DNA,bidar,karnataka
29/06/2020,28,DNA,DNA,bidar,karnataka
30/06/2020,17,DNA,DNA,bidar,karnataka
01/07/2020,8,DNA,2,bidar,karnataka
02/07/2020,32,DNA,DNA,bidar,karnataka
03/07/2020,28,DNA,1,bidar,karnataka
04/07/2020,51,DNA,6,bidar,karnataka
05/07/2020,29,DNA,9,bidar,karnataka
06/07/2020,44,DNA,8,bidar,karnataka
07/07/2020,51,DNA,4,bidar,karnataka
08/07/2020,29,DNA,1,bidar,karnataka
09/07/2020,15,DNA,DNA,bidar,karnataka
10/07/2020,19,DNA,3,bidar,karnataka
11/07/2020,63,DNA,1,bidar,karnataka
12/07/2020,62,DNA,DNA,bidar,karnataka
13/07/2020,23,DNA,DNA,bidar,karnataka
14/07/2020,42,DNA,DNA,bidar,karnataka
15/07/2020,35,DNA,DNA,bidar,karnataka
16/07/2020,53,DNA,2,bidar,karnataka
17/07/2020,69,DNA,DNA,bidar,karnataka
18/07/2020,72,DNA,1,bidar,karnataka
19/07/2020,45,DNA,3,bidar,karnataka
20/07/2020,26,DNA,4,bidar,karnataka
21/07/2020,66,DNA,2,bidar,karnataka
22/07/2020,DNA,DNA,3,bidar,karnataka
23/07/2020,DNA,DNA,3,bidar,karnataka
24/07/2020,DNA,DNA,DNA,bidar,karnataka
25/07/2020,DNA,DNA,DNA,bidar,karnataka
26/07/2020,DNA,DNA,DNA,bidar,karnataka
27/07/2020,DNA,DNA,1,bidar,karnataka
28/07/2020,DNA,DNA,2,bidar,karnataka
29/07/2020,DNA,DNA,DNA,bidar,karnataka
30/07/2020,DNA,DNA,2,bidar,karnataka
31/07/2020,DNA,DNA,2,bidar,karnataka
01/08/2020,DNA,DNA,4,bidar,karnataka
02/08/2020,DNA,DNA,DNA,bidar,karnataka
03/08/2020,DNA,DNA,3,bidar,karnataka
04/08/2020,DNA,DNA,3,bidar,karnataka
05/08/2020,DNA,DNA,2,bidar,karnataka
06/08/2020,DNA,DNA,3,bidar,karnataka
07/08/2020,DNA,DNA,1,bidar,karnataka
08/08/2020,DNA,DNA,2,bidar,karnataka
09/08/2020,DNA,DNA,4,bidar,karnataka
10/08/2020,DNA,DNA,1,bidar,karnataka
11/08/2020,DNA,DNA,2,bidar,karnataka
12/08/2020,DNA,DNA,3,bidar,karnataka
13/08/2020,DNA,DNA,DNA,bidar,karnataka
14/08/2020,DNA,DNA,1,bidar,karnataka
15/08/2020,DNA,DNA,3,bidar,karnataka
16/08/2020,DNA,DNA,1,bidar,karnataka
17/08/2020,DNA,DNA,DNA,bidar,karnataka
18/08/2020,DNA,DNA,8,bidar,karnataka
19/08/2020,DNA,DNA,3,bidar,karnataka
20/08/2020,DNA,DNA,DNA,bidar,karnataka
21/08/2020,DNA,DNA,4,bidar,karnataka
22/08/2020,DNA,DNA,4,bidar,karnataka
23/08/2020,DNA,DNA,DNA,bidar,karnataka
24/08/2020,DNA,DNA,1,bidar,karnataka
25/08/2020,DNA,DNA,DNA,bidar,karnataka
26/08/2020,DNA,DNA,2,bidar,karnataka
27/08/2020,DNA,DNA,3,bidar,karnataka
28/08/2020,DNA,DNA,DNA,bidar,karnataka
29/08/2020,DNA,DNA,DNA,bidar,karnataka
30/08/2020,DNA,DNA,1,bidar,karnataka
31/08/2020,DNA,DNA,1,bidar,karnataka
01/09/2020,DNA,DNA,DNA,bidar,karnataka
02/09/2020,DNA,DNA,1,bidar,karnataka
03/09/2020,DNA,DNA,DNA,bidar,karnataka
04/09/2020,DNA,DNA,3,bidar,karnataka
05/09/2020,DNA,DNA,DNA,bidar,karnataka
06/09/2020,DNA,DNA,DNA,bidar,karnataka
07/09/2020,DNA,DNA,DNA,bidar,karnataka
08/09/2020,DNA,DNA,DNA,bidar,karnataka
09/09/2020,DNA,DNA,DNA,bidar,karnataka
10/09/2020,DNA,DNA,DNA,bidar,karnataka
11/09/2020,DNA,DNA,DNA,bidar,karnataka
12/09/2020,DNA,DNA,DNA,bidar,karnataka
13/09/2020,DNA,DNA,DNA,bidar,karnataka
14/09/2020,DNA,DNA,DNA,bidar,karnataka
15/09/2020,DNA,DNA,DNA,bidar,karnataka
16/09/2020,DNA,DNA,DNA,bidar,karnataka
17/09/2020,DNA,DNA,DNA,bidar,karnataka
18/09/2020,DNA,DNA,DNA,bidar,karnataka
19/09/2020,DNA,DNA,DNA,bidar,karnataka
20/09/2020,DNA,DNA,DNA,bidar,karnataka
21/09/2020,DNA,DNA,DNA,bidar,karnataka
22/09/2020,DNA,DNA,DNA,bidar,karnataka
23/09/2020,DNA,DNA,DNA,bidar,karnataka
24/09/2020,DNA,DNA,DNA,bidar,karnataka
25/09/2020,DNA,DNA,DNA,bidar,karnataka
26/09/2020,DNA,DNA,DNA,bidar,karnataka
27/09/2020,DNA,DNA,DNA,bidar,karnataka
28/09/2020,DNA,DNA,DNA,bidar,karnataka
29/09/2020,DNA,DNA,DNA,bidar,karnataka
30/09/2020,DNA,DNA,DNA,bidar,karnataka
01/10/2020,DNA,DNA,DNA,bidar,karnataka
02/10/2020,DNA,DNA,DNA,bidar,karnataka
03/10/2020,DNA,DNA,DNA,bidar,karnataka
04/10/2020,DNA,DNA,DNA,bidar,karnataka
05/10/2020,DNA,DNA,DNA,bidar,karnataka
06/10/2020,DNA,DNA,DNA,bidar,karnataka
07/10/2020,DNA,DNA,DNA,bidar,karnataka
08/10/2020,DNA,DNA,DNA,bidar,karnataka
09/10/2020,DNA,DNA,DNA,bidar,karnataka
10/10/2020,DNA,DNA,DNA,bidar,karnataka
11/10/2020,DNA,DNA,DNA,bidar,karnataka
12/10/2020,DNA,DNA,DNA,bidar,karnataka
13/10/2020,DNA,DNA,DNA,bidar,karnataka
14/10/2020,DNA,DNA,DNA,bidar,karnataka
15/10/2020,DNA,DNA,DNA,bidar,karnataka
16/10/2020,DNA,DNA,DNA,bidar,karnataka
17/10/2020,DNA,DNA,DNA,bidar,karnataka
18/10/2020,DNA,DNA,DNA,bidar,karnataka
19/10/2020,DNA,DNA,DNA,bidar,karnataka
20/10/2020,DNA,DNA,DNA,bidar,karnataka
21/10/2020,DNA,DNA,DNA,bidar,karnataka
22/10/2020,DNA,DNA,DNA,bidar,karnataka
23/10/2020,DNA,DNA,DNA,bidar,karnataka
24/10/2020,DNA,DNA,DNA,bidar,karnataka
25/10/2020,DNA,DNA,DNA,bidar,karnataka
26/10/2020,DNA,DNA,DNA,bidar,karnataka
27/10/2020,DNA,DNA,DNA,bidar,karnataka
28/10/2020,DNA,DNA,DNA,bidar,karnataka
29/10/2020,DNA,DNA,DNA,bidar,karnataka
30/10/2020,DNA,DNA,DNA,bidar,karnataka
31/10/2020,DNA,DNA,DNA,bidar,karnataka
01/11/2020,DNA,DNA,DNA,bidar,karnataka
02/11/2020,DNA,DNA,DNA,bidar,karnataka
03/11/2020,DNA,DNA,DNA,bidar,karnataka
04/11/2020,DNA,DNA,DNA,bidar,karnataka
05/11/2020,DNA,DNA,DNA,bidar,karnataka
06/11/2020,DNA,DNA,DNA,bidar,karnataka
07/11/2020,DNA,DNA,DNA,bidar,karnataka
08/11/2020,DNA,DNA,DNA,bidar,karnataka
09/11/2020,DNA,DNA,DNA,bidar,karnataka
10/11/2020,DNA,DNA,DNA,bidar,karnataka
11/11/2020,DNA,DNA,DNA,bidar,karnataka
12/11/2020,DNA,DNA,DNA,bidar,karnataka
13/11/2020,DNA,DNA,DNA,bidar,karnataka
14/11/2020,DNA,DNA,DNA,bidar,karnataka
15/11/2020,DNA,DNA,DNA,bidar,karnataka
16/11/2020,DNA,DNA,DNA,bidar,karnataka
17/11/2020,DNA,DNA,DNA,bidar,karnataka
18/11/2020,DNA,DNA,DNA,bidar,karnataka
19/11/2020,DNA,DNA,DNA,bidar,karnataka
20/11/2020,DNA,DNA,DNA,bidar,karnataka
21/11/2020,DNA,DNA,DNA,bidar,karnataka
22/11/2020,DNA,DNA,DNA,bidar,karnataka
23/11/2020,DNA,DNA,DNA,bidar,karnataka
24/11/2020,DNA,DNA,DNA,bidar,karnataka
25/11/2020,DNA,DNA,DNA,bidar,karnataka
26/11/2020,DNA,DNA,DNA,bidar,karnataka
27/11/2020,DNA,DNA,DNA,bidar,karnataka
28/11/2020,DNA,DNA,DNA,bidar,karnataka
29/11/2020,DNA,DNA,DNA,bidar,karnataka
30/11/2020,DNA,DNA,DNA,bidar,karnataka
01/12/2020,DNA,DNA,DNA,bidar,karnataka
02/12/2020,DNA,DNA,DNA,bidar,karnataka
03/12/2020,DNA,DNA,DNA,bidar,karnataka
04/12/2020,DNA,DNA,DNA,bidar,karnataka
05/12/2020,DNA,DNA,DNA,bidar,karnataka
06/12/2020,DNA,DNA,DNA,bidar,karnataka
07/12/2020,DNA,DNA,DNA,bidar,karnataka
08/12/2020,DNA,DNA,DNA,bidar,karnataka
09/12/2020,DNA,DNA,DNA,bidar,karnataka
10/12/2020,DNA,DNA,DNA,bidar,karnataka
11/12/2020,DNA,DNA,DNA,bidar,karnataka
12/12/2020,DNA,DNA,DNA,bidar,karnataka
13/12/2020,DNA,DNA,DNA,bidar,karnataka
14/12/2020,DNA,DNA,DNA,bidar,karnataka
15/12/2020,DNA,DNA,DNA,bidar,karnataka
16/12/2020,DNA,DNA,DNA,bidar,karnataka
17/12/2020,DNA,DNA,DNA,bidar,karnataka
18/12/2020,DNA,DNA,DNA,bidar,karnataka
19/12/2020,DNA,DNA,DNA,bidar,karnataka
20/12/2020,DNA,DNA,DNA,bidar,karnataka
21/12/2020,DNA,DNA,DNA,bidar,karnataka
22/12/2020,DNA,DNA,DNA,bidar,karnataka
23/12/2020,DNA,DNA,DNA,bidar,karnataka
24/12/2020,DNA,DNA,DNA,bidar,karnataka
25/12/2020,DNA,DNA,DNA,bidar,karnataka
26/12/2020,DNA,DNA,DNA,bidar,karnataka
27/12/2020,DNA,DNA,DNA,bidar,karnataka
28/12/2020,DNA,DNA,DNA,bidar,karnataka
29/12/2020,DNA,DNA,DNA,bidar,karnataka
30/12/2020,DNA,DNA,DNA,bidar,karnataka
31/12/2020,DNA,DNA,DNA,bidar,karnataka

In [7]:
#state wise segregation

state_list = data.Detected_State.unique()

state_data = dict()
for states in state_list:
    state_data.update({states:0})
state_data

{'Kerala': 0,
 'Delhi': 0,
 'Telangana': 0,
 'Rajasthan': 0,
 'Haryana': 0,
 'Uttar Pradesh': 0,
 'Ladakh': 0,
 'Tamil Nadu': 0,
 'Jammu and Kashmir': 0,
 'Karnataka': 0,
 'Maharashtra': 0,
 'Andhra Pradesh': 0,
 'Odisha': 0,
 'Puducherry': 0,
 'West Bengal': 0,
 'Chandigarh': 0,
 'Chhattisgarh': 0,
 'Punjab': 0,
 'Gujarat': 0,
 'Himachal Pradesh': 0,
 'Madhya Pradesh': 0,
 'Bihar': 0,
 'Uttarakhand': 0,
 'Manipur': 0,
 'Mizoram': 0,
 'Goa': 0,
 'Andaman and Nicobar Islands': 0,
 'Jharkhand': 0,
 'Assam': 0,
 'Tripura': 0,
 'Meghalaya': 0,
 'Dadra and Nagar Haveli and Daman and Diu': 0,
 'Sikkim': 0,
 'Arunachal Pradesh': 0}

In [9]:
#state-wise calender dataframe 

for state in state_data:
    cal_dat = pd.DataFrame(columns=['Date_Announced','Total_Infections','Total_Recoveries','Total_Deceased','State'])
    cal_dat['Date_Announced'] = dates
    cal_dat.set_index('Date_Announced',inplace=True)
    
    buff_list = pd.DataFrame(hospitalized_data.loc[data['Detected_State']==state])
    grouped =  (buff_list.groupby('Date_Announced').groups)
    for i,j in grouped.items():
        grouped[i] = len(list(j))    

    for i in cal_dat.index:
        for j,k in grouped.items():
            if i == j:
                x = (cal_dat.loc[i,['Total_Infections']])
                if np.isnan(x['Total_Infections']):
                    cal_dat.loc[i,['Total_Infections']] = k
                else:
                    cal_dat.loc[i,['Total_Infections']] = x['Total_Infections'] + k
        cal_dat.loc[i,['State']] = state
        
    
    buff_list = pd.DataFrame(recovered_data.loc[data['Detected_State']==state])
    grouped =  (buff_list.groupby('Date_Announced').groups)
    for i,j in grouped.items():
        grouped[i] = len(list(j))    

    for i in cal_dat.index:
        for j,k in grouped.items():
            if i == j:
                x = (cal_dat.loc[i,['Total_Recoveries']])
                if np.isnan(x['Total_Recoveries']):
                    cal_dat.loc[i,['Total_Recoveries']] = k
                else:
                    cal_dat.loc[i,['Total_Recoveries']] = x['Total_Recoveries'] + k
        
    
    buff_list = pd.DataFrame(deceased_data.loc[data['Detected_State']==state])
    grouped =  (buff_list.groupby('Date_Announced').groups)
    for i,j in grouped.items():
        grouped[i] = len(list(j))    

    for i in cal_dat.index:
        for j,k in grouped.items():
            if i == j:
                x = (cal_dat.loc[i,['Total_Deceased']])
                if np.isnan(x['Total_Deceased']):
                    cal_dat.loc[i,['Total_Deceased']] = k
                else:
                    cal_dat.loc[i,['Total_Deceased']] = x['Total_Deceased'] + k
        
            
    cal_dat['Total_Recoveries'] = cal_dat['Total_Recoveries'].replace(np.nan, 'DNA')
    cal_dat['Total_Deceased'] = cal_dat['Total_Deceased'].replace(np.nan, 'DNA') 
    cal_dat['Total_Infections'] = cal_dat['Total_Infections'].replace(np.nan, 'DNA') 
    state_data[state] = cal_dat

In [10]:
state_data

{'Kerala':                Total_Infections Total_Recoveries Total_Deceased   State
 Date_Announced
 01/01/2020                  NaN              NaN            NaN  Kerala
 02/01/2020                  NaN              NaN            NaN  Kerala
 03/01/2020                  NaN              NaN            NaN  Kerala
 04/01/2020                  NaN              NaN            NaN  Kerala
 05/01/2020                  NaN              NaN            NaN  Kerala
 ...                         ...              ...            ...     ...
 27/12/2020                  NaN              NaN            NaN  Kerala
 28/12/2020                  NaN              NaN            NaN  Kerala
 29/12/2020                  NaN              NaN            NaN  Kerala
 30/12/2020                  NaN              NaN            NaN  Kerala
 31/12/2020                  NaN              NaN            NaN  Kerala

 [366 rows x 4 columns],
 'Delhi':                Total_Infections Total_Recoveries Total_Deceased  State
 Date_Announced
 01/01/2020                  NaN              NaN            NaN  Delhi
 02/01/2020                  NaN              NaN            NaN  Delhi
 03/01/2020                  NaN              NaN            NaN  Delhi
 04/01/2020                  NaN              NaN            NaN  Delhi
 05/01/2020                  NaN              NaN            NaN  Delhi
 ...                         ...              ...            ...    ...
 27/12/2020                  NaN              NaN            NaN  Delhi
 28/12/2020                  NaN              NaN            NaN  Delhi
 29/12/2020                  NaN              NaN            NaN  Delhi
 30/12/2020                  NaN              NaN            NaN  Delhi
 31/12/2020                  NaN              NaN            NaN  Delhi

 [366 rows x 4 columns],
 'Telangana':                Total_Infections Total_Recoveries Total_Deceased      State
 Date_Announced
 01/01/2020                  NaN              NaN            NaN  Telangana
 02/01/2020                  NaN              NaN            NaN  Telangana
 03/01/2020                  NaN              NaN            NaN  Telangana
 04/01/2020                  NaN              NaN            NaN  Telangana
 05/01/2020                  NaN              NaN            NaN  Telangana
 ...                         ...              ...            ...        ...
 27/12/2020                  NaN              NaN            NaN  Telangana
 28/12/2020                  NaN              NaN            NaN  Telangana
 29/12/2020                  NaN              NaN            NaN  Telangana
 30/12/2020                  NaN              NaN            NaN  Telangana
 31/12/2020                  NaN              NaN            NaN  Telangana

 [366 rows x 4 columns],
 'Rajasthan':                Total_Infections Total_Recoveries Total_Deceased      State
 Date_Announced
 01/01/2020                  NaN              NaN            NaN  Rajasthan
 02/01/2020                  NaN              NaN            NaN  Rajasthan
 03/01/2020                  NaN              NaN            NaN  Rajasthan
 04/01/2020                  NaN              NaN            NaN  Rajasthan
 05/01/2020                  NaN              NaN            NaN  Rajasthan
 ...                         ...              ...            ...        ...
 27/12/2020                  NaN              NaN            NaN  Rajasthan
 28/12/2020                  NaN              NaN            NaN  Rajasthan
 29/12/2020                  NaN              NaN            NaN  Rajasthan
 30/12/2020                  NaN              NaN            NaN  Rajasthan
 31/12/2020                  NaN              NaN            NaN  Rajasthan

 [366 rows x 4 columns],
 'Haryana':                Total_Infections Total_Recoveries Total_Deceased    State
 Date_Announced
 01/01/2020                  NaN              NaN            NaN  Haryana
 02/01/2020                  NaN              NaN            NaN  Haryana
 03/01/2020                  NaN              NaN            NaN  Haryana
 04/01/2020                  NaN              NaN            NaN  Haryana
 05/01/2020                  NaN              NaN            NaN  Haryana
 ...                         ...              ...            ...      ...
 27/12/2020                  NaN              NaN            NaN  Haryana
 28/12/2020                  NaN              NaN            NaN  Haryana
 29/12/2020                  NaN              NaN            NaN  Haryana
 30/12/2020                  NaN              NaN            NaN  Haryana
 31/12/2020                  NaN              NaN            NaN  Haryana

 [366 rows x 4 columns],
 'Uttar Pradesh':                Total_Infections Total_Recoveries Total_Deceased          State
 Date_Announced
 01/01/2020                  NaN              NaN            NaN  Uttar Pradesh
 02/01/2020                  NaN              NaN            NaN  Uttar Pradesh
 03/01/2020                  NaN              NaN            NaN  Uttar Pradesh
 04/01/2020                  NaN              NaN            NaN  Uttar Pradesh
 05/01/2020                  NaN              NaN            NaN  Uttar Pradesh
 ...                         ...              ...            ...            ...
 27/12/2020                  NaN              NaN            NaN  Uttar Pradesh
 28/12/2020                  NaN              NaN            NaN  Uttar Pradesh
 29/12/2020                  NaN              NaN            NaN  Uttar Pradesh
 30/12/2020                  NaN              NaN            NaN  Uttar Pradesh
 31/12/2020                  NaN              NaN            NaN  Uttar Pradesh

 [366 rows x 4 columns],
 'Ladakh':                Total_Infections Total_Recoveries Total_Deceased   State
 Date_Announced
 01/01/2020                  NaN              NaN            NaN  Ladakh
 02/01/2020                  NaN              NaN            NaN  Ladakh
 03/01/2020                  NaN              NaN            NaN  Ladakh
 04/01/2020                  NaN              NaN            NaN  Ladakh
 05/01/2020                  NaN              NaN            NaN  Ladakh
 ...                         ...              ...            ...     ...
 27/12/2020                  NaN              NaN            NaN  Ladakh
 28/12/2020                  NaN              NaN            NaN  Ladakh
 29/12/2020                  NaN              NaN            NaN  Ladakh
 30/12/2020                  NaN              NaN            NaN  Ladakh
 31/12/2020                  NaN              NaN            NaN  Ladakh

 [366 rows x 4 columns],
 'Tamil Nadu':                Total_Infections Total_Recoveries Total_Deceased       State
 Date_Announced
 01/01/2020                  NaN              NaN            NaN  Tamil Nadu
 02/01/2020                  NaN              NaN            NaN  Tamil Nadu
 03/01/2020                  NaN              NaN            NaN  Tamil Nadu
 04/01/2020                  NaN              NaN            NaN  Tamil Nadu
 05/01/2020                  NaN              NaN            NaN  Tamil Nadu
 ...                         ...              ...            ...         ...
 27/12/2020                  NaN              NaN            NaN  Tamil Nadu
 28/12/2020                  NaN              NaN            NaN  Tamil Nadu
 29/12/2020                  NaN              NaN            NaN  Tamil Nadu
 30/12/2020                  NaN              NaN            NaN  Tamil Nadu
 31/12/2020                  NaN              NaN            NaN  Tamil Nadu

 [366 rows x 4 columns],
 'Jammu and Kashmir':                Total_Infections Total_Recoveries Total_Deceased  \
 Date_Announced
 01/01/2020                  NaN              NaN            NaN
 02/01/2020                  NaN              NaN            NaN
 03/01/2020                  NaN              NaN            NaN
 04/01/2020                  NaN              NaN            NaN
 05/01/2020                  NaN              NaN            NaN
 ...                         ...              ...            ...
 27/12/2020                  NaN              NaN            NaN
 28/12/2020                  NaN              NaN            NaN
 29/12/2020                  NaN              NaN            NaN
 30/12/2020                  NaN              NaN            NaN
 31/12/2020                  NaN              NaN            NaN

                             State
 Date_Announced
 01/01/2020      Jammu and Kashmir
 02/01/2020      Jammu and Kashmir
 03/01/2020      Jammu and Kashmir
 04/01/2020      Jammu and Kashmir
 05/01/2020      Jammu and Kashmir
 ...                           ...
 27/12/2020      Jammu and Kashmir
 28/12/2020      Jammu and Kashmir
 29/12/2020      Jammu and Kashmir
 30/12/2020      Jammu and Kashmir
 31/12/2020      Jammu and Kashmir

 [366 rows x 4 columns],
 'Karnataka':                Total_Infections Total_Recoveries Total_Deceased      State
 Date_Announced
 01/01/2020                  NaN              NaN            NaN  Karnataka
 02/01/2020                  NaN              NaN            NaN  Karnataka
 03/01/2020                  NaN              NaN            NaN  Karnataka
 04/01/2020                  NaN              NaN            NaN  Karnataka
 05/01/2020                  NaN              NaN            NaN  Karnataka
 ...                         ...              ...            ...        ...
 27/12/2020                  NaN              NaN            NaN  Karnataka
 28/12/2020                  NaN              NaN            NaN  Karnataka
 29/12/2020                  NaN              NaN            NaN  Karnataka
 30/12/2020                  NaN              NaN            NaN  Karnataka
 31/12/2020                  NaN              NaN            NaN  Karnataka

 [366 rows x 4 columns],
 'Maharashtra':                Total_Infections Total_Recoveries Total_Deceased        State
 Date_Announced
 01/01/2020                  NaN              NaN            NaN  Maharashtra
 02/01/2020                  NaN              NaN            NaN  Maharashtra
 03/01/2020                  NaN              NaN            NaN  Maharashtra
 04/01/2020                  NaN              NaN            NaN  Maharashtra
 05/01/2020                  NaN              NaN            NaN  Maharashtra
 ...                         ...              ...            ...          ...
 27/12/2020                  NaN              NaN            NaN  Maharashtra
 28/12/2020                  NaN              NaN            NaN  Maharashtra
 29/12/2020                  NaN              NaN            NaN  Maharashtra
 30/12/2020                  NaN              NaN            NaN  Maharashtra
 31/12/2020                  NaN              NaN            NaN  Maharashtra

 [366 rows x 4 columns],
 'Andhra Pradesh':                Total_Infections Total_Recoveries Total_Deceased  \
 Date_Announced
 01/01/2020                  NaN              NaN            NaN
 02/01/2020                  NaN              NaN            NaN
 03/01/2020                  NaN              NaN            NaN
 04/01/2020                  NaN              NaN            NaN
 05/01/2020                  NaN              NaN            NaN
 ...                         ...              ...            ...
 27/12/2020                  NaN              NaN            NaN
 28/12/2020                  NaN              NaN            NaN
 29/12/2020                  NaN              NaN            NaN
 30/12/2020                  NaN              NaN            NaN
 31/12/2020                  NaN              NaN            NaN

                          State
 Date_Announced
 01/01/2020      Andhra Pradesh
 02/01/2020      Andhra Pradesh
 03/01/2020      Andhra Pradesh
 04/01/2020      Andhra Pradesh
 05/01/2020      Andhra Pradesh
 ...                        ...
 27/12/2020      Andhra Pradesh
 28/12/2020      Andhra Pradesh
 29/12/2020      Andhra Pradesh
 30/12/2020      Andhra Pradesh
 31/12/2020      Andhra Pradesh

 [366 rows x 4 columns],
 'Odisha':                Total_Infections Total_Recoveries Total_Deceased   State
 Date_Announced
 01/01/2020                  NaN              NaN            NaN  Odisha
 02/01/2020                  NaN              NaN            NaN  Odisha
 03/01/2020                  NaN              NaN            NaN  Odisha
 04/01/2020                  NaN              NaN            NaN  Odisha
 05/01/2020                  NaN              NaN            NaN  Odisha
 ...                         ...              ...            ...     ...
 27/12/2020                  NaN              NaN            NaN  Odisha
 28/12/2020                  NaN              NaN            NaN  Odisha
 29/12/2020                  NaN              NaN            NaN  Odisha
 30/12/2020                  NaN              NaN            NaN  Odisha
 31/12/2020                  NaN              NaN            NaN  Odisha

 [366 rows x 4 columns],
 'Puducherry':                Total_Infections Total_Recoveries Total_Deceased       State
 Date_Announced
 01/01/2020                  NaN              NaN            NaN  Puducherry
 02/01/2020                  NaN              NaN            NaN  Puducherry
 03/01/2020                  NaN              NaN            NaN  Puducherry
 04/01/2020                  NaN              NaN            NaN  Puducherry
 05/01/2020                  NaN              NaN            NaN  Puducherry
 ...                         ...              ...            ...         ...
 27/12/2020                  NaN              NaN            NaN  Puducherry
 28/12/2020                  NaN              NaN            NaN  Puducherry
 29/12/2020                  NaN              NaN            NaN  Puducherry
 30/12/2020                  NaN              NaN            NaN  Puducherry
 31/12/2020                  NaN              NaN            NaN  Puducherry

 [366 rows x 4 columns],
 'West Bengal':                Total_Infections Total_Recoveries Total_Deceased        State
 Date_Announced
 01/01/2020                  NaN              NaN            NaN  West Bengal
 02/01/2020                  NaN              NaN            NaN  West Bengal
 03/01/2020                  NaN              NaN            NaN  West Bengal
 04/01/2020                  NaN              NaN            NaN  West Bengal
 05/01/2020                  NaN              NaN            NaN  West Bengal
 ...                         ...              ...            ...          ...
 27/12/2020                  NaN              NaN            NaN  West Bengal
 28/12/2020                  NaN              NaN            NaN  West Bengal
 29/12/2020                  NaN              NaN            NaN  West Bengal
 30/12/2020                  NaN              NaN            NaN  West Bengal
 31/12/2020                  NaN              NaN            NaN  West Bengal

 [366 rows x 4 columns],
 'Chandigarh':                Total_Infections Total_Recoveries Total_Deceased       State
 Date_Announced
 01/01/2020                  NaN              NaN            NaN  Chandigarh
 02/01/2020                  NaN              NaN            NaN  Chandigarh
 03/01/2020                  NaN              NaN            NaN  Chandigarh
 04/01/2020                  NaN              NaN            NaN  Chandigarh
 05/01/2020                  NaN              NaN            NaN  Chandigarh
 ...                         ...              ...            ...         ...
 27/12/2020                  NaN              NaN            NaN  Chandigarh
 28/12/2020                  NaN              NaN            NaN  Chandigarh
 29/12/2020                  NaN              NaN            NaN  Chandigarh
 30/12/2020                  NaN              NaN            NaN  Chandigarh
 31/12/2020                  NaN              NaN            NaN  Chandigarh

 [366 rows x 4 columns],
 'Chhattisgarh':                Total_Infections Total_Recoveries Total_Deceased         State
 Date_Announced
 01/01/2020                  NaN              NaN            NaN  Chhattisgarh
 02/01/2020                  NaN              NaN            NaN  Chhattisgarh
 03/01/2020                  NaN              NaN            NaN  Chhattisgarh
 04/01/2020                  NaN              NaN            NaN  Chhattisgarh
 05/01/2020                  NaN              NaN            NaN  Chhattisgarh
 ...                         ...              ...            ...           ...
 27/12/2020                  NaN              NaN            NaN  Chhattisgarh
 28/12/2020                  NaN              NaN            NaN  Chhattisgarh
 29/12/2020                  NaN              NaN            NaN  Chhattisgarh
 30/12/2020                  NaN              NaN            NaN  Chhattisgarh
 31/12/2020                  NaN              NaN            NaN  Chhattisgarh

 [366 rows x 4 columns],
 'Punjab':                Total_Infections Total_Recoveries Total_Deceased   State
 Date_Announced
 01/01/2020                  NaN              NaN            NaN  Punjab
 02/01/2020                  NaN              NaN            NaN  Punjab
 03/01/2020                  NaN              NaN            NaN  Punjab
 04/01/2020                  NaN              NaN            NaN  Punjab
 05/01/2020                  NaN              NaN            NaN  Punjab
 ...                         ...              ...            ...     ...
 27/12/2020                  NaN              NaN            NaN  Punjab
 28/12/2020                  NaN              NaN            NaN  Punjab
 29/12/2020                  NaN              NaN            NaN  Punjab
 30/12/2020                  NaN              NaN            NaN  Punjab
 31/12/2020                  NaN              NaN            NaN  Punjab

 [366 rows x 4 columns],
 'Gujarat':                Total_Infections Total_Recoveries Total_Deceased    State
 Date_Announced
 01/01/2020                  NaN              NaN            NaN  Gujarat
 02/01/2020                  NaN              NaN            NaN  Gujarat
 03/01/2020                  NaN              NaN            NaN  Gujarat
 04/01/2020                  NaN              NaN            NaN  Gujarat
 05/01/2020                  NaN              NaN            NaN  Gujarat
 ...                         ...              ...            ...      ...
 27/12/2020                  NaN              NaN            NaN  Gujarat
 28/12/2020                  NaN              NaN            NaN  Gujarat
 29/12/2020                  NaN              NaN            NaN  Gujarat
 30/12/2020                  NaN              NaN            NaN  Gujarat
 31/12/2020                  NaN              NaN            NaN  Gujarat

 [366 rows x 4 columns],
 'Himachal Pradesh':                Total_Infections Total_Recoveries Total_Deceased  \
 Date_Announced
 01/01/2020                  NaN              NaN            NaN
 02/01/2020                  NaN              NaN            NaN
 03/01/2020                  NaN              NaN            NaN
 04/01/2020                  NaN              NaN            NaN
 05/01/2020                  NaN              NaN            NaN
 ...                         ...              ...            ...
 27/12/2020                  NaN              NaN            NaN
 28/12/2020                  NaN              NaN            NaN
 29/12/2020                  NaN              NaN            NaN
 30/12/2020                  NaN              NaN            NaN
 31/12/2020                  NaN              NaN            NaN

                            State
 Date_Announced
 01/01/2020      Himachal Pradesh
 02/01/2020      Himachal Pradesh
 03/01/2020      Himachal Pradesh
 04/01/2020      Himachal Pradesh
 05/01/2020      Himachal Pradesh
 ...                          ...
 27/12/2020      Himachal Pradesh

In [12]:
pd.set_option('display.max_rows',466)
state_data['Karnataka']

               Total_Infections Total_Recoveries Total_Deceased      State
Date_Announced
01/01/2020                  NaN              NaN            NaN  Karnataka
02/01/2020                  NaN              NaN            NaN  Karnataka
03/01/2020                  NaN              NaN            NaN  Karnataka
04/01/2020                  NaN              NaN            NaN  Karnataka
05/01/2020                  NaN              NaN            NaN  Karnataka
06/01/2020                  NaN              NaN            NaN  Karnataka
07/01/2020                  NaN              NaN            NaN  Karnataka
08/01/2020                  NaN              NaN            NaN  Karnataka
09/01/2020                  NaN              NaN            NaN  Karnataka
10/01/2020                  NaN              NaN            NaN  Karnataka
11/01/2020                  NaN              NaN            NaN  Karnataka
12/01/2020                  NaN              NaN            NaN  Karnataka
13/01/2020                  NaN              NaN            NaN  Karnataka
14/01/2020                  NaN              NaN            NaN  Karnataka
15/01/2020                  NaN              NaN            NaN  Karnataka
16/01/2020                  NaN              NaN            NaN  Karnataka
17/01/2020                  NaN              NaN            NaN  Karnataka
18/01/2020                  NaN              NaN            NaN  Karnataka
19/01/2020                  NaN              NaN            NaN  Karnataka
20/01/2020                  NaN              NaN            NaN  Karnataka
21/01/2020                  NaN              NaN            NaN  Karnataka
22/01/2020                  NaN              NaN            NaN  Karnataka
23/01/2020                  NaN              NaN            NaN  Karnataka
24/01/2020                  NaN              NaN            NaN  Karnataka
25/01/2020                  NaN              NaN            NaN  Karnataka
26/01/2020                  NaN              NaN            NaN  Karnataka
27/01/2020                  NaN              NaN            NaN  Karnataka
28/01/2020                  NaN              NaN            NaN  Karnataka
29/01/2020                  NaN              NaN            NaN  Karnataka
30/01/2020                  NaN              NaN            NaN  Karnataka
31/01/2020                  NaN              NaN            NaN  Karnataka
01/02/2020                  NaN              NaN            NaN  Karnataka
02/02/2020                  NaN              NaN            NaN  Karnataka
03/02/2020                  NaN              NaN            NaN  Karnataka
04/02/2020                  NaN              NaN            NaN  Karnataka
05/02/2020                  NaN              NaN            NaN  Karnataka
06/02/2020                  NaN              NaN            NaN  Karnataka
07/02/2020                  NaN              NaN            NaN  Karnataka
08/02/2020                  NaN              NaN            NaN  Karnataka
09/02/2020                  NaN              NaN            NaN  Karnataka
10/02/2020                  NaN              NaN            NaN  Karnataka
11/02/2020                  NaN              NaN            NaN  Karnataka
12/02/2020                  NaN              NaN            NaN  Karnataka
13/02/2020                  NaN              NaN            NaN  Karnataka
14/02/2020                  NaN              NaN            NaN  Karnataka
15/02/2020                  NaN              NaN            NaN  Karnataka
16/02/2020                  NaN              NaN            NaN  Karnataka
17/02/2020                  NaN              NaN            NaN  Karnataka
18/02/2020                  NaN              NaN            NaN  Karnataka
19/02/2020                  NaN              NaN            NaN  Karnataka
20/02/2020                  NaN              NaN            NaN  Karnataka
21/02/2020                  NaN              NaN            NaN  Karnataka
22/02/2020                  NaN              NaN            NaN  Karnataka
23/02/2020                  NaN              NaN            NaN  Karnataka
24/02/2020                  NaN              NaN            NaN  Karnataka
25/02/2020                  NaN              NaN            NaN  Karnataka
26/02/2020                  NaN              NaN            NaN  Karnataka
27/02/2020                  NaN              NaN            NaN  Karnataka
28/02/2020                  NaN              NaN            NaN  Karnataka
29/02/2020                  NaN              NaN            NaN  Karnataka
01/03/2020                  NaN              NaN            NaN  Karnataka
02/03/2020                  NaN              NaN            NaN  Karnataka
03/03/2020                  NaN              NaN            NaN  Karnataka
04/03/2020                  NaN              NaN            NaN  Karnataka
05/03/2020                  NaN              NaN            NaN  Karnataka
06/03/2020                  NaN              NaN            NaN  Karnataka
07/03/2020                  NaN              NaN            NaN  Karnataka
08/03/2020                  NaN              NaN            NaN  Karnataka
09/03/2020                  NaN                1            NaN  Karnataka
10/03/2020                  NaN                3            NaN  Karnataka
11/03/2020                  NaN              NaN            NaN  Karnataka
12/03/2020                  NaN                1            NaN  Karnataka
13/03/2020                  NaN              NaN              1  Karnataka
14/03/2020                  NaN              NaN            NaN  Karnataka
15/03/2020                  NaN              NaN            NaN  Karnataka
16/03/2020                  NaN                1            NaN  Karnataka
17/03/2020                  NaN                4            NaN  Karnataka
18/03/2020                  NaN                3            NaN  Karnataka
19/03/2020                  NaN                1            NaN  Karnataka
20/03/2020                  NaN              NaN            NaN  Karnataka
21/03/2020                    2                3            NaN  Karnataka
22/03/2020                  NaN                6            NaN  Karnataka
23/03/2020                    2                5            NaN  Karnataka
24/03/2020                    1                7            NaN  Karnataka
25/03/2020                    4                6            NaN  Karnataka
26/03/2020                    2                1              1  Karnataka
27/03/2020                    4                4              1  Karnataka
28/03/2020                    5                7            NaN  Karnataka
29/03/2020                    4                3            NaN  Karnataka
30/03/2020                    2                3            NaN  Karnataka
31/03/2020                   12                1            NaN  Karnataka
01/04/2020                    8                1            NaN  Karnataka
02/04/2020                   14              NaN            NaN  Karnataka
03/04/2020                    3              NaN              1  Karnataka
04/04/2020                   16              NaN            NaN  Karnataka
05/04/2020                    7              NaN            NaN  Karnataka
06/04/2020                   12              NaN            NaN  Karnataka
07/04/2020                   11              NaN              1  Karnataka
08/04/2020                    5              NaN              1  Karnataka
09/04/2020                   15              NaN              1  Karnataka
10/04/2020                    9              NaN              1  Karnataka
11/04/2020                    8              NaN            NaN  Karnataka
12/04/2020                   17              NaN            NaN  Karnataka
13/04/2020                   15              NaN            NaN  Karnataka
14/04/2020                   13              NaN            NaN  Karnataka
15/04/2020                   18              NaN              1  Karnataka
16/04/2020                   34              NaN            NaN  Karnataka
17/04/2020                   44              NaN            NaN  Karnataka
18/04/2020                   24              NaN              1  Karnataka
19/04/2020                    5              NaN              1  Karnataka
20/04/2020                   18              NaN            NaN  Karnataka
21/04/2020                   10              NaN            NaN  Karnataka
22/04/2020                    9              NaN            NaN  Karnataka
23/04/2020                   18              NaN            NaN  Karnataka
24/04/2020                   29              NaN            NaN  Karnataka
25/04/2020                   26              NaN            NaN  Karnataka
26/04/2020                    3              NaN            NaN  Karnataka
27/04/2020                    9              NaN              1  Karnataka
28/04/2020                   11              NaN            NaN  Karnataka
29/04/2020                   12              NaN              1  Karnataka
30/04/2020                   30              NaN              1  Karnataka
01/05/2020                   24              NaN            NaN  Karnataka
02/05/2020                   12              NaN              3  Karnataka
03/05/2020                   13              NaN            NaN  Karnataka
04/05/2020                   37              NaN              2  Karnataka
05/05/2020                   22              NaN              2  Karnataka
06/05/2020                   20              NaN            NaN  Karnataka
07/05/2020                   12              NaN              1  Karnataka
08/05/2020                   48              NaN            NaN  Karnataka
09/05/2020                   41              NaN            NaN  Karnataka
10/05/2020                   54              NaN              1  Karnataka
11/05/2020                   11              NaN            NaN  Karnataka
12/05/2020                   63              NaN            NaN  Karnataka
13/05/2020                   26              NaN              2  Karnataka
14/05/2020                   28              NaN              2  Karnataka
15/05/2020                   69              NaN              1  Karnataka
16/05/2020                   36              NaN            NaN  Karnataka
17/05/2020                   54              NaN              1  Karnataka
18/05/2020                   99              NaN            NaN  Karnataka
19/05/2020                  149              NaN              3  Karnataka
20/05/2020                   67              NaN              1  Karnataka
21/05/2020                  125              NaN            NaN  Karnataka
22/05/2020                  108              NaN            NaN  Karnataka
23/05/2020                  216              NaN            NaN  Karnataka
24/05/2020                  130              NaN            NaN  Karnataka
25/05/2020                   93              NaN              1  Karnataka
26/05/2020                  101              NaN            NaN  Karnataka
27/05/2020                  135              NaN              1  Karnataka
28/05/2020                  115              NaN            NaN  Karnataka
29/05/2020                  248              NaN            NaN  Karnataka
30/05/2020                  141              NaN            NaN  Karnataka
31/05/2020                  299              NaN              2  Karnataka
01/06/2020                  187              NaN              1  Karnataka
02/06/2020                  388              NaN            NaN  Karnataka
03/06/2020                  267              NaN              1  Karnataka
04/06/2020                  257              NaN              4  Karnataka
05/06/2020                  515              NaN            NaN  Karnataka
06/06/2020                  378              NaN              2  Karnataka
07/06/2020                  239              NaN              2  Karnataka
08/06/2020                  308              NaN              3  Karnataka
09/06/2020                  161              NaN              2  Karnataka
10/06/2020                  120              NaN              3  Karnataka
11/06/2020                  204              NaN              3  Karnataka
12/06/2020                  271              NaN              7  Karnataka
13/06/2020                  308              NaN              3  Karnataka
14/06/2020                  176              NaN              5  Karnataka
15/06/2020                  213              NaN              2  Karnataka
16/06/2020                  317              NaN              7  Karnataka
17/06/2020                  204              NaN              8  Karnataka
18/06/2020                  210              NaN             12  Karnataka
19/06/2020                  337              NaN             10  Karnataka
20/06/2020                  416              NaN              9  Karnataka
21/06/2020                  453              NaN              5  Karnataka
22/06/2020                  249              NaN              5  Karnataka
23/06/2020                  322              NaN              8  Karnataka
24/06/2020                  397              NaN             14  Karnataka
25/06/2020                  442              NaN              6  Karnataka
26/06/2020                  445              NaN             10  Karnataka
27/06/2020                  918              NaN             11  Karnataka
28/06/2020                 1267              NaN             16  Karnataka
29/06/2020                 1105              NaN             19  Karnataka
30/06/2020                  947              NaN             20  Karnataka
01/07/2020                 1272              NaN              7  Karnataka
02/07/2020                 1502              NaN             19  Karnataka
03/07/2020                 1694              NaN             21  Karnataka
04/07/2020                 1839              NaN             42  Karnataka
05/07/2020                 1925              NaN             37  Karnataka
06/07/2020                 1843              NaN             30  Karnataka
07/07/2020                 1498              NaN             15  Karnataka
08/07/2020                 2062              NaN             54  Karnataka
09/07/2020                 2228              NaN             17  Karnataka
10/07/2020                 2313              NaN             57  Karnataka
11/07/2020                 2798              NaN             70  Karnataka
12/07/2020                 2627              NaN             71  Karnataka
13/07/2020                 2738              NaN             73  Karnataka
14/07/2020                 2496              NaN             87  Karnataka
15/07/2020                 3176              NaN             87  Karnataka
16/07/2020                 4169              NaN            104  Karnataka
17/07/2020                 3693              NaN            115  Karnataka
18/07/2020                 4537              NaN             93  Karnataka
19/07/2020                 4120              NaN             91  Karnataka
20/07/2020                 3648              NaN             72  Karnataka
21/07/2020                 3649              NaN             61  Karnataka
22/07/2020                  NaN              NaN             55  Karnataka
23/07/2020                  NaN              NaN             97  Karnataka
24/07/2020                  NaN              NaN            110  Karnataka
25/07/2020                  NaN              NaN             72  Karnataka
26/07/2020                  NaN              NaN             82  Karnataka
27/07/2020                  NaN              NaN             75  Karnataka
28/07/2020                  NaN              NaN            102  Karnataka
29/07/2020                  NaN              NaN            NaN  Karnataka
30/07/2020                  NaN              NaN             83  Karnataka
31/07/2020                  NaN              NaN             84  Karnataka
01/08/2020                  NaN              NaN             98  Karnataka
02/08/2020                  NaN              NaN             84  Karnataka
03/08/2020                  NaN              NaN             98  Karnataka
04/08/2020                  NaN              NaN            110  Karnataka
05/08/2020                  NaN              NaN            100  Karnataka
06/08/2020                  NaN              NaN             93  Karnataka
07/08/2020                  NaN              NaN            101  Karnataka
08/08/2020                  NaN              NaN             93  Karnataka
09/08/2020                  NaN              NaN            107  Karnataka
10/08/2020                  NaN              NaN            114  Karnataka
11/08/2020                  NaN              NaN             86  Karnataka
12/08/2020                  NaN              NaN            113  Karnataka
13/08/2020                  NaN              NaN            103  Karnataka
14/08/2020                  NaN              NaN            104  Karnataka
15/08/2020                  NaN              NaN            114  Karnataka
16/08/2020                  NaN              NaN            124  Karnataka
17/08/2020                  NaN              NaN            115  Karnataka
18/08/2020                  NaN              NaN            139  Karnataka
19/08/2020                  NaN              NaN            126  Karnataka
20/08/2020                  NaN              NaN            102  Karnataka
21/08/2020                  NaN              NaN             93  Karnataka
22/08/2020                  NaN              NaN             93  Karnataka
23/08/2020                  NaN              NaN             68  Karnataka
24/08/2020                  NaN              NaN            130  Karnataka
25/08/2020                  NaN              NaN            148  Karnataka
26/08/2020                  NaN              NaN            133  Karnataka
27/08/2020                  NaN              NaN            141  Karnataka
28/08/2020                  NaN              NaN            136  Karnataka
29/08/2020                  NaN              NaN            115  Karnataka
30/08/2020                  NaN              NaN            106  Karnataka
31/08/2020                  NaN              NaN            113  Karnataka
01/09/2020                  NaN              NaN            135  Karnataka
02/09/2020                  NaN              NaN            113  Karnataka
03/09/2020                  NaN              NaN            104  Karnataka
04/09/2020                  NaN              NaN            116  Karnataka
05/09/2020                  NaN              NaN            128  Karnataka
06/09/2020                  NaN              NaN            NaN  Karnataka
07/09/2020                  NaN              NaN            NaN  Karnataka
08/09/2020                  NaN              NaN            NaN  Karnataka
09/09/2020                  NaN              NaN            NaN  Karnataka
10/09/2020                  NaN              NaN            NaN  Karnataka
11/09/2020                  NaN              NaN            NaN  Karnataka
12/09/2020                  NaN              NaN            NaN  Karnataka
13/09/2020                  NaN              NaN            NaN  Karnataka
14/09/2020                  NaN              NaN            NaN  Karnataka
15/09/2020                  NaN              NaN            NaN  Karnataka
16/09/2020                  NaN              NaN            NaN  Karnataka
17/09/2020                  NaN              NaN            NaN  Karnataka
18/09/2020                  NaN              NaN            NaN  Karnataka
19/09/2020                  NaN              NaN            NaN  Karnataka
20/09/2020                  NaN              NaN            NaN  Karnataka
21/09/2020                  NaN              NaN            NaN  Karnataka

In [ ]:
-----------------------------------------------------**-----------------------------------------------------------

In [5]:
#Other datasets

df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 300911 entries, 0 to 300910
Data columns (total 23 columns):
Age Bracket                                  113961 non-null object
Backup Notes                                 361 non-null object
Contracted from which Patient (Suspected)    1938 non-null object
Current Status                               300905 non-null object
Date Announced                               300909 non-null object
Detected City                                13841 non-null object
Detected District                            291105 non-null object
Detected State                               300898 non-null object
Entry_ID                                     272726 non-null float64
Estimated Onset Date                         0 non-null float64
Gender                                       116592 non-null object
Nationality                                  1554 non-null object
Notes                                        114332 non-null object
Num Cases                                    300904 non-null float64
Patient Number                               99793 non-null float64
Source_1                                     296892 non-null object
Source_2                                     6811 non-null object
Source_3                                     710 non-null object
State Patient Number                         114172 non-null object
State code                                   300893 non-null object
Status Change Date                           27780 non-null object
Type of transmission                         2990 non-null object
filename                                     300911 non-null object
dtypes: float64(4), object(19)
memory usage: 52.8+ MB

In [6]:
pd.set_option('max_rows', None)
case_time

,Date,Daily Confirmed,Total Confirmed,Daily Recovered,Total Recovered,Daily Deceased,Total Deceased
0,30 January,1,1,0,0,0,0
1,31 January,0,1,0,0,0,0
2,01 February,0,1,0,0,0,0
3,02 February,1,2,0,0,0,0
4,03 February,1,3,0,0,0,0
5,04 February,0,3,0,0,0,0
6,05 February,0,3,0,0,0,0
7,06 February,0,3,0,0,0,0
8,07 February,0,3,0,0,0,0
9,08 February,0,3,0,0,0,0
10,09 February,0,3,0,0,0,0
11,10 February,0,3,0,0,0,0
12,11 February,0,3,0,0,0,0
13,12 February,0,3,0,0,0,0
14,13 February,0,3,1,1,0,0
15,14 February,0,3,0,1,0,0
16,15 February,0,3,0,1,0,0
17,16 February,0,3,1,2,0,0
18,17 February,0,3,0,2,0,0
19,18 February,0,3,0,2,0,0
20,19 February,0,3,0,2,0,0
21,20 February,0,3,1,3,0,0
22,21 February,0,3,0,3,0,0
23,22 February,0,3,0,3,0,0
24,23 February,0,3,0,3,0,0
25,24 February,0,3,0,3,0,0
26,25 February,0,3,0,3,0,0
27,26 February,0,3,0,3,0,0
28,27 February,0,3,0,3,0,0
29,28 February,0,3,0,3,0,0
30,29 February,0,3,0,3,0,0
31,01 March,0,3,0,3,0,0
32,02 March,2,5,0,3,0,0
33,03 March,1,6,0,3,0,0
34,04 March,22,28,0,3,0,0
35,05 March,2,30,0,3,0,0
36,06 March,1,31,0,3,0,0
37,07 March,3,34,0,3,0,0
38,08 March,5,39,0,3,0,0
39,09 March,9,48,0,3,0,0
40,10 March,15,63,1,4,0,0
41,11 March,8,71,0,4,0,0
42,12 March,10,81,0,4,1,1
43,13 March,10,91,6,10,0,1
44,14 March,11,102,0,10,1,2
45,15 March,10,112,3,13,0,2
46,16 March,14,126,1,14,0,2
47,17 March,20,146,1,15,1,3
48,18 March,25,171,0,15,0,3
49,19 March,27,198,5,20,1,4
50,20 March,58,256,3,23,0,4
51,21 March,78,334,0,23,0,4
52,22 March,69,403,0,23,3,7
53,23 March,94,497,2,25,2,9
54,24 March,74,571,15,40,1,10
55,25 March,86,657,3,43,1,11
56,26 March,73,730,7,50,5,16
57,27 March,153,883,25,75,3,19
58,28 March,136,1019,10,85,5,24
59,29 March,120,1139,17,102,3,27
60,30 March,187,1326,35,137,14,41
61,31 March,309,1635,13,150,6,47
62,01 April,424,2059,19,169,6,53
63,02 April,486,2545,22,191,16,69
64,03 April,560,3105,39,230,14,83
65,04 April,579,3684,56,286,13,96
66,05 April,609,4293,43,329,22,118
67,06 April,484,4777,65,394,16,134
68,07 April,573,5350,75,469,27,161
69,08 April,565,5915,96,565,20,181
70,09 April,813,6728,70,635,46,227
71,10 April,871,7599,151,786,22,249
72,11 April,854,8453,186,972,41,290
73,12 April,758,9211,114,1086,42,332
74,13 April,1243,10454,112,1198,27,359
75,14 April,1031,11485,167,1365,37,396
76,15 April,886,12371,144,1509,27,423
77,16 April,1061,13432,258,1767,26,449
78,17 April,922,14354,273,2040,38,487
79,18 April,1371,15725,426,2466,35,522
80,19 April,1580,17305,388,2854,38,560
81,20 April,1239,18544,419,3273,33,593
82,21 April,1537,20081,703,3976,53,646
83,22 April,1292,21373,394,4370,36,682
84,23 April,1667,23040,642,5012,40,722
85,24 April,1408,24448,484,5496,59,781
86,25 April,1835,26283,442,5938,44,825
87,26 April,1607,27890,585,6523,56,881
88,27 April,1568,29458,580,7103,58,939
89,28 April,1902,31360,636,7739,69,1008
90,29 April,1705,33065,690,8429,71,1079
91,30 April,1801,34866,630,9059,75,1154
92,01 May,2396,37262,962,10021,77,1231
93,02 May,2564,39826,831,10852,92,1323
94,03 May,2952,42778,911,11763,140,1463
95,04 May,3656,46434,1082,12845,103,1566
96,05 May,2971,49405,1295,14140,128,1694
97,06 May,3602,53007,1161,15301,91,1785
98,07 May,3344,56351,1475,16776,104,1889
99,08 May,3339,59690,1111,17887,97,1986
100,09 May,3175,62865,1414,19301,115,2101
101,10 May,4311,67176,1669,20970,112,2213
102,11 May,3592,70768,1579,22549,81,2294
103,12 May,3562,74330,1905,24454,120,2414
104,13 May,3726,78056,1963,26417,137,2551
105,14 May,3991,82047,1594,28011,97,2648
106,15 May,3808,85855,2234,30245,104,2752
107,16 May,4794,90649,4012,34257,120,2872
108,17 May,5049,95698,2538,36795,152,3024
109,18 May,4628,100326,2482,39277,131,3155
110,19 May,6154,106480,3032,42309,146,3301
111,20 May,5720,112200,3113,45422,134,3435
112,21 May,6023,118223,3131,48553,148,3583
113,22 May,6536,124759,3280,51833,142,3725
114,23 May,6667,131424,2576,54409,142,3867
115,24 May,7111,138537,3285,57694,156,4023
116,25 May,6414,144951,3012,60706,150,4173
117,26 May,5907,150858,3585,64291,173,4346
118,27 May,7246,158104,3434,67725,188,4534
119,28 May,7254,165358,3171,70896,176,4710
120,29 May,8138,173496,11735,82631,269,4979
121,30 May,8364,181860,4303,86934,205,5184
122,31 May,8789,190649,4928,91862,222,5406
123,01 June,7723,198372,3882,95744,201,5607
124,02 June,8812,207187,4531,100275,222,5829
125,03 June,9689,216876,3789,104064,259,6088
126,04 June,9847,226723,4390,108454,274,6362
127,05 June,9472,236195,4770,113224,286,6648
128,06 June,10408,246603,5433,118657,297,6945
129,07 June,10882,257485,5191,123848,261,7206
130,08 June,8536,266021,5171,129019,271,7477
131,09 June,9981,276002,5634,134653,272,7749
132,10 June,11156,287158,6275,140928,358,8107
133,11 June,11135,298293,6044,146972,394,8501
134,12 June,11306,309599,7263,154235,388,8889
135,13 June,12039,321638,8092,162327,309,9198
136,14 June,11405,333043,7358,169685,324,9522
137,15 June,10032,343075,10639,180324,396,9918
138,16 June,11086,354161,7226,187550,2004,11922
139,17 June,13108,367269,6890,194440,341,12263
140,18 June,13829,381098,10741,205181,343,12606
141,19 June,14740,395838,9029,214210,364,12970
142,20 June,15918,411753,13974,228184,308,13278
143,21 June,15151,426904,9075,237259,426,13704
144,22 June,13560,440464,10879,248138,312,14016
145,23 June,15656,456120,10462,258600,468,14484
146,24 June,16868,472988,13089,271689,424,14908
147,25 June,18205,491193,13983,285672,401,15309
148,26 June,18255,509448,10246,295918,381,15690
149,27 June,20142,529590,14229,310147,414,16104
150,28 June,19610,549200,11631,321778,384,16488
151,29 June,18339,567539,13497,335275,417,16905
152,30 June,18256,585795,12565,347840,506,17411
153,01 July,19429,605224,12064,359904,438,17849
154,02 July,21947,627171,19999,379903,378,18227
155,03 July,22718,649889,14417,394320,444,18671
156,04 July,24018,673907,14746,409066,611,19282
157,05 July,23942,697849,15829,424895,421,19703
158,06 July,22500,720349,15315,440210,473,20176
159,07 July,23147,743496,16836,457046,479,20655
160,08 July,25561,769057,19508,476554,492,21147
161,09 July,25790,794847,19408,495962,479,21626
162,10 July,27762,822609,20289,516251,520,22146
163,11 July,27757,850366,19981,536232,543,22689
164,12 July,29106,879472,18198,554430,500,23189
165,13 July,28178,907650,17683,572113,541,23730
166,14 July,29917,937567,20977,593090,587,24317
167,15 July,32607,970174,20646,613736,614,24931
168,16 July,35468,1005642,22867,636603,680,25611
169,17 July,34820,1040462,17476,654079,676,26287
170,18 July,37411,1077873,23583,677662,543,26830
171,19 July,40235,1118108,22730,700392,675,27505
172,20 July,36806,1154914,24303,724695,596,28101
173,21 July,39170,1194084,27589,752284,671,28772
174,22 July,45601,1239685,31875,784159,1130,29902
175,23 July,48443,1288128,33326,817485,755,30657
176,24 July,48888,1337016,32514,849999,763,31420
177,25 July,50072,1387088,37125,887124,703,32123
178,26 July,48932,1436020,31512,918636,704,32827
179,27 July,46484,1482504,34354,952990,642,33469
180,28 July,49631,1532135,35683,988673,774,34243
181,29 July,52479,1584614,32886,1021559,775,35018
182,30 July,54968,1639582,37425,1058984,784,35802
183,31 July,57486,1697068,36554,1095538,764,36566
184,01 August,55117,1752185,51368,1146906,854,37420
185,02 August,52672,1804857,40355,1187261,760,38180
186,03 August,50488,1855345,43070,1230331,806,38986
187,04 August,51282,1906627,51220,1281551,849,39835
188,05 August,56626,1963253,45583,1327134,919,40754
189,06 August,62170,2025423,50141,1377275,899,41653
190,07 August,61455,2086878,50387,1427662,936,42589
191,08 August,65156,2152034,52135,1479797,875,43464
192,09 August,62117,2214151,54474,1534271,1013,44477
193,10 August,53016,2267167,47362,1581633,887,45364
194,11 August,61252,2328419,56461,1638094,835,46199
195,12 August,67066,2395485,57759,1695853,950,47149
196,13 August,64141,2459626,54776,1750629,1006,48155
197,14 August,65610,2525236,56920,1807549,989,49144
198,15 August,63986,2589222,53116,1860665,952,50096
199,16 August,58096,2647318,57404,1918069,952,51048
200,17 August,54298,2701616,58172,1976241,880,51928
201,18 August,65024,2766640,60455,2036696,1099,53027
202,19 August,69196,2835836,59365,2096061,979,54006
203,20 August,68518,2904354,61873,2157934,981,54987
204,21 August,69029,2973383,62858,2220792,953,55940
205,22 August,70067,3043450,59101,2279893,918,56858
206,23 August,61749,3105199,56896,2336789,846,57704
207,24 August,59696,3164895,66305,2403094,854,58558
208,25 August,66873,3231768,64151,2467245,1066,59624
209,26 August,75995,3307763,56191,2523436,1017,60641
210,27 August,76827,3384590,59620,2583056,1066,61707
211,28 August,76657,3461247,64475,2647531,1019,62726
212,29 August,78479,3539726,64982,2712513,943,63669
213,30 August,79461,3619187,60422,2772935,960,64629
214,31 August,68766,3687953,64435,2837370,816,65445
215,01 September,78168,3766121,62145,2899515,892,66337
216,02 September,82860,3848981,67874,2967389,913,67250
217,03 September,84156,3933137,67491,3034880,979,68229
218,04 September,87115,4020252,69625,3104505,950,69179
219,05 September,90600,4110852,73161,3177666,916,70095
220,06 September,91723,4202575,69624,3247290,1008,71103

,Date,Status,TT,AN,AP,AR,AS,BR,CH,CT,...,PB,RJ,SK,TN,TG,TR,UP,UT,WB,UN
0,14-Mar-20,Confirmed,81,0,1,0,0,0,0,0,...,1,3,0,1,1,0,12,0,0,0
1,14-Mar-20,Recovered,9,0,0,0,0,0,0,0,...,0,1,0,0,0,0,4,0,0,0
2,14-Mar-20,Deceased,2,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
3,15-Mar-20,Confirmed,27,0,0,0,0,0,0,0,...,0,1,0,0,2,0,1,0,0,0
4,15-Mar-20,Recovered,4,0,0,0,0,0,0,0,...,0,2,0,0,1,0,0,0,0,0
5,15-Mar-20,Deceased,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
6,16-Mar-20,Confirmed,15,0,0,0,0,0,0,0,...,0,0,0,0,1,0,0,1,0,0
7,16-Mar-20,Recovered,1,0,0,0,0,0,0,0,...,0,0,0,1,0,0,0,0,0,0
8,16-Mar-20,Deceased,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
9,17-Mar-20,Confirmed,11,0,0,0,0,0,0,0,...,0,0,0,0,1,0,2,0,1,0
10,17-Mar-20,Recovered,1,0,0,0,0,0,0,0,...,0,0,0,0,0,0,1,0,0,0
11,17-Mar-20,Deceased,1,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
12,18-Mar-20,Confirmed,37,0,0,0,0,0,0,0,...,1,3,0,1,8,0,2,1,0,0
13,18-Mar-20,Recovered,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
14,18-Mar-20,Deceased,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
15,19-Mar-20,Confirmed,27,0,2,0,0,0,1,1,...,0,2,0,1,3,0,3,1,0,0
16,19-Mar-20,Recovered,5,0,0,0,0,0,0,0,...,0,0,0,0,0,0,4,0,0,0
17,19-Mar-20,Deceased,1,0,0,0,0,0,0,0,...,1,0,0,0,0,0,0,0,0,0
18,20-Mar-20,Confirmed,58,0,0,0,0,0,4,0,...,1,8,0,0,3,0,4,0,1,0
19,20-Mar-20,Recovered,3,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
20,20-Mar-20,Deceased,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
21,21-Mar-20,Confirmed,78,0,2,0,0,0,0,0,...,10,7,0,3,2,0,4,0,2,0
22,21-Mar-20,Recovered,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
23,21-Mar-20,Deceased,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
24,22-Mar-20,Confirmed,67,0,1,0,0,2,1,0,...,8,4,0,3,6,0,2,0,3,0
25,22-Mar-20,Recovered,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
26,22-Mar-20,Deceased,3,0,0,0,0,1,0,0,...,0,0,0,0,0,0,0,0,0,0
27,23-Mar-20,Confirmed,102,0,1,0,0,1,1,0,...,2,4,0,3,6,0,2,1,0,0
28,23-Mar-20,Recovered,12,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
29,23-Mar-20,Deceased,2,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,1,0
30,24-Mar-20,Confirmed,64,0,1,0,0,0,0,0,...,6,0,0,6,4,0,3,0,2,0
31,24-Mar-20,Recovered,5,0,0,0,0,0,0,0,...,0,0,0,0,0,0,2,0,0,0
32,24-Mar-20,Deceased,1,0,0,0,0,0,0,0,...,0,0,0,1,0,0,0,0,0,0
33,25-Mar-20,Confirmed,90,0,2,0,0,1,0,2,...,2,6,0,8,4,0,3,1,0,0
34,25-Mar-20,Recovered,3,0,1,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
35,25-Mar-20,Deceased,1,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
36,26-Mar-20,Confirmed,65,1,1,0,0,3,0,3,...,2,2,0,3,3,0,4,0,1,0
37,26-Mar-20,Recovered,7,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
38,26-Mar-20,Deceased,5,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
39,27-Mar-20,Confirmed,164,5,2,0,0,2,1,0,...,5,10,0,9,15,0,7,0,5,0
40,27-Mar-20,Recovered,26,0,0,0,0,0,0,0,...,1,0,0,1,0,0,0,0,0,0
41,27-Mar-20,Deceased,3,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
42,28-Mar-20,Confirmed,143,3,6,0,0,2,0,1,...,0,4,0,4,8,0,16,1,3,0
43,28-Mar-20,Recovered,9,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,1,0,0
44,28-Mar-20,Deceased,5,0,0,0,0,0,0,0,...,0,0,0,0,1,0,0,0,0,0
45,29-Mar-20,Confirmed,110,0,2,0,0,4,0,0,...,0,5,0,8,3,0,7,1,3,0
46,29-Mar-20,Recovered,5,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
47,29-Mar-20,Deceased,3,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
48,30-Mar-20,Confirmed,187,1,2,0,0,0,5,1,...,3,20,0,17,7,0,24,0,1,0
49,30-Mar-20,Recovered,49,0,0,0,0,0,0,0,...,0,0,0,2,13,0,6,1,0,0
50,30-Mar-20,Deceased,13,0,0,0,0,0,0,0,...,2,0,0,0,5,0,0,0,1,0
51,31-Mar-20,Confirmed,309,0,21,0,1,6,2,1,...,1,14,0,57,20,0,8,0,15,0
52,31-Mar-20,Recovered,15,0,0,0,0,0,0,2,...,0,0,0,2,0,0,0,0,3,0
53,31-Mar-20,Deceased,6,0,0,0,0,0,0,0,...,1,0,0,0,0,0,0,0,1,0
54,01-Apr-20,Confirmed,424,0,67,0,15,3,2,0,...,4,27,0,110,30,0,13,0,0,0
55,01-Apr-20,Recovered,16,0,1,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
56,01-Apr-20,Deceased,9,0,0,0,0,0,0,0,...,0,0,0,0,3,0,2,0,0,0
57,02-Apr-20,Confirmed,486,0,38,1,0,5,1,0,...,1,13,0,75,27,0,11,3,16,0
58,02-Apr-20,Recovered,22,0,0,0,0,3,0,1,...,0,0,0,0,3,0,0,0,0,0
59,02-Apr-20,Deceased,14,0,0,0,0,0,0,0,...,1,0,0,0,0,0,0,0,0,0
60,03-Apr-20,Confirmed,560,0,15,0,7,2,0,0,...,6,46,0,102,75,0,46,6,0,0
61,03-Apr-20,Recovered,38,0,0,0,0,0,0,0,...,0,0,0,0,15,0,0,0,0,0
62,03-Apr-20,Deceased,14,0,1,0,0,0,0,0,...,0,0,0,0,2,0,0,0,0,0
63,04-Apr-20,Confirmed,579,0,28,0,3,1,0,1,...,12,27,0,74,43,0,60,6,0,0
64,04-Apr-20,Recovered,56,0,0,0,0,0,3,0,...,2,22,0,2,1,0,4,0,0,0
65,04-Apr-20,Deceased,13,0,0,0,0,0,0,0,...,0,1,0,2,0,0,0,0,0,0
66,05-Apr-20,Confirmed,609,0,64,0,0,0,0,0,...,3,60,0,86,62,0,44,4,27,0
67,05-Apr-20,Recovered,43,0,3,0,0,0,2,5,...,1,0,0,0,0,0,0,2,7,0
68,05-Apr-20,Deceased,22,0,0,0,0,0,0,0,...,2,0,0,2,0,0,1,0,0,0
69,06-Apr-20,Confirmed,484,0,47,0,0,0,0,0,...,11,35,0,50,30,1,27,5,0,0
70,06-Apr-20,Recovered,65,0,0,0,0,6,0,0,...,0,0,0,5,12,0,0,0,0,0
71,06-Apr-20,Deceased,16,0,2,0,0,0,0,0,...,0,1,0,1,0,0,0,0,0,0
72,07-Apr-20,Confirmed,572,0,11,0,2,6,0,0,...,20,42,0,69,40,0,27,0,11,0
73,07-Apr-20,Recovered,75,0,0,0,0,6,2,1,...,10,0,0,6,0,0,0,0,3,0
74,07-Apr-20,Deceased,27,0,1,0,0,0,0,0,...,1,0,0,1,0,0,0,0,0,0
75,08-Apr-20,Confirmed,565,1,34,0,0,1,0,0,...,7,40,0,48,49,0,29,4,8,0
76,08-Apr-20,Recovered,96,0,1,0,0,0,0,0,...,0,20,0,2,0,0,10,1,0,0
77,08-Apr-20,Deceased,20,0,0,0,0,0,0,0,...,1,1,0,1,0,0,1,0,2,0
78,09-Apr-20,Confirmed,813,0,15,0,1,19,0,8,...,24,80,0,96,18,0,49,0,4,0
79,09-Apr-20,Recovered,70,10,4,0,0,0,0,0,...,4,15,0,6,0,0,0,0,3,0
80,09-Apr-20,Deceased,46,0,2,0,0,0,0,0,...,1,0,0,0,1,0,0,0,0,0
81,10-Apr-20,Confirmed,871,0,18,0,0,2,1,0,...,21,98,0,77,16,1,23,0,13,0
82,10-Apr-20,Recovered,151,0,0,0,0,0,0,0,...,2,0,0,17,0,0,1,0,0,0
83,10-Apr-20,Deceased,22,0,0,0,1,0,0,0,...,1,0,0,1,0,0,0,0,0,0
84,11-Apr-20,Confirmed,854,0,24,0,0,4,0,7,...,7,139,0,58,16,0,19,0,10,0
85,11-Apr-20,Recovered,186,0,0,0,0,0,0,0,...,0,56,0,0,51,0,13,0,0,0
86,11-Apr-20,Deceased,40,0,0,0,0,0,0,0,...,1,6,0,1,2,0,1,0,0,0
87,12-Apr-20,Confirmed,758,0,15,0,1,0,2,6,...,12,104,0,106,28,0,31,0,8,0
88,12-Apr-20,Recovered,114,0,2,0,0,11,0,1,...,3,5,0,6,7,0,0,0,3,0
89,12-Apr-20,Deceased,42,0,1,0,0,0,0,0,...,0,2,0,1,2,0,0,0,2,0
90,13-Apr-20,Confirmed,1243,0,19,0,2,2,0,0,...,6,93,0,98,61,0,75,0,18,0
91,13-Apr-20,Recovered,112,0,0,0,0,2,0,0,...,2,0,0,8,0,0,4,2,10,0
92,13-Apr-20,Deceased,27,0,0,0,0,0,0,0,...,0,0,0,0,1,0,0,0,0,0
93,14-Apr-20,Confirmed,1031,0,45,0,1,0,0,2,...,8,108,0,31,52,0,102,2,38,0
94,14-Apr-20,Recovered,167,0,4,0,0,1,0,3,...,2,26,0,23,7,0,1,2,7,0
95,14-Apr-20,Deceased,37,0,4,0,0,0,0,0,...,1,0,0,1,1,0,3,0,0,0
96,15-Apr-20,Confirmed,886,0,41,0,0,6,0,0,...,2,71,0,38,6,0,75,0,23,0
97,15-Apr-20,Recovered,144,0,4,1,2,0,2,4,...,0,0,0,37,8,1,7,0,1,0
98,15-Apr-20,Deceased,27,0,3,0,0,0,0,0,...,0,0,0,2,0,0,3,0,0,0
99,16-Apr-20,Confirmed,1061,0,9,0,2,11,0,3,...,11,55,0,25,50,0,70,0,18,0
100,16-Apr-20,Recovered,258,1,0,0,3,8,0,6,...,2,17,0,62,68,0,11,0,5,0
101,16-Apr-20,Deceased,26,0,0,0,0,0,0,0,...,1,0,0,1,0,0,2,0,3,0
102,17-Apr-20,Confirmed,922,1,38,0,0,2,0,0,...,14,98,0,56,66,0,44,3,24,0
103,17-Apr-20,Recovered,273,0,15,0,4,0,0,1,...,1,19,0,103,0,0,14,0,9,0
104,17-Apr-20,Deceased,38,0,0,0,0,0,0,0,...,0,6,0,0,0,0,1,0,0,0
105,18-Apr-20,Confirmed,1371,2,31,0,0,1,2,0,...,23,122,0,49,43,0,126,2,32,0
106,18-Apr-20,Recovered,426,0,7,0,3,5,0,1,...,1,17,0,82,0,0,26,0,4,0
107,18-Apr-20,Deceased,35,0,2,0,0,1,0,0,...,2,4,0,0,0,0,0,0,2,0
108,19-Apr-20,Confirmed,1580,1,44,0,0,10,3,0,...,10,127,0,105,49,0,125,2,23,0
109,19-Apr-20,Recovered,388,0,23,0,5,0,4,0,...,6,5,0,46,0,0,19,2,7,0
110,19-Apr-20,Deceased,38,0,1,0,0,0,0,0,...,0,2,0,0,3,0,3,0,0,0
111,20-Apr-20,Confirmed,1239,1,75,0,0,17,0,0,...,1,98,0,43,14,0,84,2,29,0
112,20-Apr-20,Recovered,419,0,27,0,2,0,1,0,...,1,0,0,46,0,0,13,7,4,0
113,20-Apr-20,Deceased,33,0,3,0,0,0,0,0,...,0,2,0,2,2,0,1,0,0,0
114,21-Apr-20,Confirmed,1537,1,35,0,0,13,1,0,...,6,159,0,76,56,0,153,0,53,0
115,21-Apr-20,Recovered,703,0,4,0,0,0,0,0,...,11,69,0,178,8,0,22,1,7,0
116,21-Apr-20,Deceased,53,0,2,0,0,0,0,0,...,0,1,0,1,0,0,3,0,3,0
117,22-Apr-20,Confirmed,1292,1,56,0,0,17,0,0,...,27,153,0,33,15,0,112,0,31,0
118,22-Apr-20,Recovered,394,0,24,0,0,0,0,3,...,4,70,0,27,0,0,11,4,0,0
119,22-Apr-20,Deceased,36,0,2,0,0,0,0,0,...,0,1,0,0,1,0,0,0,0,0
120,23-Apr-20,Confirmed,1667,4,80,0,1,27,0,0,...,5,76,0,54,27,0,61,1,33,0
121,23-Apr-20,Recovered,642,0,21,0,0,2,0,2,...,13,107,0,90,58,1,33,1,6,0
122,23-Apr-20,Deceased,40,0,3,0,0,0,0,0,...,1,1,0,2,1,0,3,0,0,0
123,24-Apr-20,Confirmed,1408,7,62,0,0,53,0,0,...,15,70,0,72,13,0,111,1,58,0
124,24-Apr-20,Recovered,484,0,4,0,0,0,1,0,...,4,42,0,114,39,0,20,1,24,0
125,24-Apr-20,Deceased,59,0,2,0,0,0,0,0,...,0,4,0,2,0,0,1,0,3,0
126,25-Apr-20,Confirmed,1835,4,61,0,0,28,1,1,...,10,49,0,66,7,0,172,0,57,0
127,25-Apr-20,Recovered,442,0,26,0,0,1,0,2,...,2,20,0,94,16,0,35,1,0,0
128,25-Apr-20,Deceased,44,0,2,0,0,0,0,0,...,0,2,0,1,0,0,2,0,0,0
129,26-Apr-20,Confirmed,1607,0,81,0,0,26,8,0,...,14,102,0,64,11,0,80,3,40,0
130,26-Apr-20,Recovered,585,0,60,0,8,11,2,0,...,12,116,0,60,9,0,66,0,2,0
131,26-Apr-20,Deceased,56,0,0,0,0,0,0,0,...,1,7,0,1,0,0,3,0,2,0
132,27-Apr-20,Confirmed,1568,0,80,0,0,69,9,0,...,8,77,0,52,2,0,113,0,38,0
133,27-Apr-20,Recovered,580,0,4,0,0,0,0,0,...,14,115,0,54,16,0,72,0,0,0
134,27-Apr-20,Deceased,58,0,0,0,0,0,0,0,...,1,9,0,0,0,0,1,0,0,0
135,28-Apr-20,Confirmed,1902,0,82,0,2,20,11,1,...,12,102,0,121,6,0,67,3,48,0
136,28-Apr-20,Recovered,636,4,23,0,0,8,0,2,...,3,26,0,54,42,0,63,0,4,0
137,28-Apr-20,Deceased,69,0,0,0,0,0,0,0,...,0,2,0,1,0,0,3,0,2,0
138,29-Apr-20,Confirmed,1705,0,73,0,0,37,12,0,...,33,76,0,104,7,0,81,1,28,0
139,29-Apr-20,Recovered,690,0,29,0,2,0,0,0,...,0,44,0,82,35,0,48,2,10,0
140,29-Apr-20,Deceased,71,0,0,0,0,0,0,0,...,0,3,0,2,0,0,5,0,0,0
141,30-Apr-20,Confirmed,1802,0,71,0,5,22,6,2,...,105,144,0,161,22,1,77,2,33,0
142,30-Apr-20,Recovered,630,1,34,0,0,20,1,2,...,3,79,0,48,33,0,41,8,5,0
143,30-Apr-20,Deceased,75,0,0,0,0,0,0,0,...,1,3,0,0,3,0,1,0,11,0
144,01-May-20,Confirmed,2396,0,60,0,0,41,14,3,...,105,82,0,203,6,0,117,0,37,0
145,01-May-20,Recovered,962,0,82,0,4,14,0,0,...,4,223,0,54,22,0,103,1,15,0
146,01-May-20,Deceased,77,0,2,0,0,1,0,0,...,0,4,0,1,0,0,2,1,8,0
147,02-May-20,Confirmed,2564,0,62,0,0,15,6,0,...,187,106,0,231,17,2,159,2,127,0
148,02-May-20,Recovered,831,10,38,0,0,19,1,0,...,4,126,0,29,35,0,44,2,12,0
149,02-May-20,Deceased,92,0,0,0,0,1,0,0,...,0,6,0,1,1,0,1,0,7,0
150,03-May-20,Confirmed,2952,0,58,0,0,36,3,14,...,330,114,0,266,21,12,158,1,276,0
151,03-May-20,Recovered,911,6,47,0,0,7,0,0,...,5,114,0,38,46,0,56,0,-19,0
152,03-May-20,Deceased,140,0,0,0,0,0,1,0,...,1,3,0,1,0,0,0,0,74,0
153,04-May-20,Confirmed,3656,0,67,0,0,11,5,1,...,130,175,0,527,3,13,121,0,61,0
154,04-May-20,Recovered,1082,0,36,0,0,3,2,0,...,11,82,0,30,40,0,48,0,86,0
155,04-May-20,Deceased,103,0,0,0,0,0,0,0,...,2,6,0,1,0,0,7,0,11,0
156,05-May-20,Confirmed,2971,0,67,0,2,7,17,1,...,219,97,0,508,11,13,114,1,85,0
157,05-May-20,Recovered,1295,0,65,0,0,31,0,0,...,5,87,0,76,43,0,185,0,46,0
158,05-May-20,Deceased,128,0,1,0,0,0,0,0,...,2,12,0,2,0,0,6,0,7,0
159,06-May-20,Confirmed,3602,0,60,0,1,7,5,0,...,75,159,0,771,11,22,118,0,112,0
160,06-May-20,Recovered,1161,0,140,0,2,0,0,0,...,2,214,0,31,20,0,143,0,1,0
161,06-May-20,Deceased,91,0,2,0,0,0,0,0,...,2,4,0,2,0,0,4,0,4,0
162,07-May-20,Confirmed,3344,0,56,0,8,8,11,0,...,118,110,0,580,15,24,73,0,92,0
163,07-May-20,Recovered,1475,1,51,0,0,60,0,0,...,14,150,0,31,45,0,120,0,31,0
164,07-May-20,Deceased,104,0,2,0,0,1,0,0,...,1,6,0,2,0,0,2,0,7,0
165,08-May-20,Confirmed,3339,0,54,0,6,29,11,0,...,87,152,0,600,10,30,143,2,130,0
166,08-May-20,Recovered,1111,0,62,0,0,49,0,2,...,3,122,0,58,34,0,137,6,27,0
167,08-May-20,Deceased,97,0,3,0,1,0,1,0,...,1,4,0,3,0,0,4,0,9,0
168,09-May-20,Confirmed,3175,0,43,0,2,32,23,0,...,31,129,0,526,31,17,159,4,108,0
169,09-May-20,Recovered,1414,0,45,0,0,51,3,5,...,5,151,0,219,24,0,112,1,49,0
170,09-May-20,Deceased,115,0,3,0,-1,0,0,0,...,2,3,0,4,1,0,8,0,11,0
171,10-May-20,Confirmed,4311,0,50,0,1,96,4,0,...,61,106,0,669,33,16,94,1,153,0
172,10-May-20,Recovered,1669,0,38,0,0,36,0,6,...,9,79,0,135,0,0,154,0,45,0
173,10-May-20,Deceased,112,0,1,0,0,1,1,0,...,0,2,0,3,0,0,5,0,14,0
174,11-May-20,Confirmed,3592,0,38,0,2,42,8,0,...,54,174,0,798,79,0,106,0,124,0
175,11-May-20,Recovered,1579,0,73,0,5,23,4,4,...,2,83,0,92,50,0,105,0,82,0
176,11-May-20,Deceased,81,0,0,0,0,0,0,0,...,0,5,0,6,0,0,1,0,5,0
177,12-May-20,Confirmed,3562,0,71,0,0,130,6,0,...,37,138,0,716,51,2,91,1,110,0
178,12-May-20,Recovered,1905,0,58,0,0,5,2,1,...,3,130,0,83,21,0,115,0,113,0
179,12-May-20,Deceased,120,0,1,0,0,0,0,0,...,1,4,0,8,2,0,2,0,8,0
180,13-May-20,Confirmed,3726,0,48,0,15,74,4,0,...,10,202,0,509,41,1,94,3,117,0
181,13-May-20,Recovered,1963,0,86,0,0,18,0,1,...,29,119,0,41,117,0,92,0,90,0
182,13-May-20,Deceased,137,0,1,0,0,1,0,0,...,0,4,0,3,2,0,4,0,9,0
183,14-May-20,Confirmed,3991,0,68,0,7,46,0,1,...,11,206,0,447,47,1,144,6,87,0
184,14-May-20,Recovered,1594,0,50,0,0,12,7,1,...,23,65,0,65,13,27,107,4,66,0
185,14-May-20,Deceased,97,0,1,0,0,0,0,0,...,0,4,0,2,0,0,2,0,8,0
186,15-May-20,Confirmed,3808,0,102,0,3,34,0,6,...,-3,213,0,434,40,0,155,4,84,0
187,15-May-20,Recovered,2234,0,60,0,1,28,3,0,...,82,91,0,359,7,13,93,1,61,0
188,15-May-20,Deceased,104,0,0,0,0,0,0,0,...,0,0,0,5,0,0,7,0,10,0
189,16-May-20,Confirmed,4794,0,48,0,3,145,0,1,...,14,213,0,477,55,11,201,9,115,0
190,16-May-20,Recovered,4012,0,101,0,0,33,11,2,...,952,215,0,939,12,22,276,0,63,0
191,16-May-20,Deceased,120,0,1,0,0,1,0,0,...,0,1,0,4,0,0,9,0,7,0
192,17-May-20,Confirmed,5049,0,25,0,8,142,0,18,...,18,242,0,639,42,-2,206,1,101,0
193,17-May-20,Recovered,2538,0,103,0,1,0,0,1,...,109,111,0,634,21,21,195,1,67,0
194,17-May-20,Deceased,152,0,1,0,0,0,0,0,...,3,5,0,4,0,0,8,0,6,0
195,18-May-20,Confirmed,4628,0,52,0,15,103,5,10,...,16,305,0,536,41,0,141,4,147,0
196,18-May-20,Recovered,2482,0,96,0,0,44,3,0,...,181,163,0,234,10,4,147,0,47,0
197,18-May-20,Deceased,131,0,0,0,2,1,0,0,...,2,7,0,3,0,0,6,0,6,0
198,19-May-20,Confirmed,6154,0,57,0,42,96,3,5,...,22,338,0,688,42,8,321,15,137,814
199,19-May-20,Recovered,3032,0,69,0,0,0,3,0,...,95,119,0,489,9,27,135,0,68,0
200,19-May-20,Deceased,146,0,2,0,0,0,0,0,...,1,5,0,3,4,0,5,0,6,0
201,20-May-20,Confirmed,5720,0,71,0,31,257,3,14,...,3,170,0,743,27,0,249,15,142,282
202,20-May-20,Recovered,3113,0,43,0,7,54,79,0,...,152,67,0,987,2,0,148,1,62,0
203,20-May-20,Deceased,134,0,1,0,0,0,0,0,...,0,4,0,3,2,0,4,0,3,0
204,21-May-20,Confirmed,6023,0,45,0,22,211,16,14,...,23,212,0,776,38,2,340,19,94,307
205,21-May-20,Recovered,3131,0,41,0,6,0,42,0,...,25,81,0,400,23,32,138,0,57,0
206,21-May-20,Deceased,148,0,1,0,0,0,0,0,...,1,4,0,7,5,0,11,0,6,0
207,22-May-20,Confirmed,6536,0,62,0,15,179,1,44,...,1,267,0,786,62,0,220,8,135,217
208,22-May-20,Recovered,3280,0,26,0,0,58,0,3,...,28,195,0,846,7,4,120,0,28,0
209,22-May-20,Deceased,142,0,1,0,0,2,0,0,...,0,2,0,4,3,0,14,0,6,0
210,23-May-20,Confirmed,6663,0,47,0,121,228,6,42,...,16,248,1,759,52,16,282,91,127,279
211,23-May-20,Recovered,2576,0,48,0,2,24,1,2,...,23,106,0,363,25,0,82,2,60,0
212,23-May-20,Deceased,142,0,1,0,0,0,0,0,...,0,7,0,5,1,0,3,0,4,0
213,24-May-20,Confirmed,7111,0,66,1,46,180,37,38,...,15,286,0,765,41,3,251,73,208,439
214,24-May-20,Recovered,3285,0,62,0,1,49,0,0,...,28,62,0,833,24,13,132,3,58,0
215,24-May-20,Deceased,156,0,0,0,0,0,1,0,...,1,3,0,8,4,0,6,2,3,0
216,25-May-20,Confirmed,6414,0,106,0,156,163,4,40,...,21,272,0,805,66,4,229,32,149,304
217,25-May-20,Recovered,3012,0,51,0,5,31,8,3,...,15,208,0,407,72,0,122,0,75,0
218,25-May-20,Deceased,150,0,0,0,0,2,0,0,...,0,4,0,7,3,0,8,1,6,0
219,26-May-20,Confirmed,5907,0,97,0,134,231,12,68,...,25,236,0,646,112,34,227,51,193,328
220,26-May-20,Recovered,3585,0,125,0,0,67,0,12,...,5,220,0,611,120,0,164,6,72,0
221,26-May-20,Deceased,173,0,1,0,0,1,0,0,...,0,3,0,11,1,0,8,0,5,0
222,27-May-20,Confirmed,7246,0,134,0,101,68,1,4,...,33,280,0,817,107,10,267,69,183,1043
223,27-May-20,Recovered,3434,0,48,0,25,118,0,4,...,0,286,0,567,37,0,167,15,92,0
224,27-May-20,Deceased,188,0,1,0,0,1,0,0,...,0,3,0,6,6,0,5,0,6,0
225,28-May-20,Confirmed,7254,0,128,1,97,149,10,34,...,19,251,0,827,117,2,179,31,344,319
226,28-May-20,Recovered,3171,0,68,0,16,132,2,0,...,28,253,0,639,24,2,224,0,90,0
227,28-May-20,Deceased,176,0,1,0,0,0,0,0,...,0,7,0,12,4,0,15,0,6,0
228,29-May-20,Confirmed,8138,0,85,0,177,174,0,17,...,39,298,0,874,169,10,275,216,277,341
229,29-May-20,Recovered,11735,0,101,0,22,159,0,17,...,3,429,0,765,36,0,195,23,107,0
230,29-May-20,Deceased,269,0,1,0,0,0,0,1,...,2,4,0,9,4,0,4,0,7,0
231,30-May-20,Confirmed,8364,0,131,1,159,206,0,32,...,36,252,0,938,74,17,256,33,317,370
232,30-May-20,Recovered,4303,0,55,0,38,102,10,2,...,18,495,0,687,31,5,241,0,195,0
233,30-May-20,Deceased,205,0,0,0,0,6,0,0,...,2,9,0,6,6,0,12,1,7,0
234,31-May-20,Confirmed,8789,0,110,0,123,242,4,51,...,30,214,0,1149,199,45,374,158,371,448
235,31-May-20,Recovered,4928,0,51,0,22,209,0,12,...,20,293,0,757,16,1,192,0,187,0
236,31-May-20,Deceased,222,0,2,0,0,2,0,0,...,1,1,0,13,5,0,4,0,8,0
237,01-Jun-20,Confirmed,7723,0,105,18,146,138,4,49,...,38,269,0,1162,94,107,286,52,271,139
238,01-Jun-20,Recovered,3882,0,34,0,99,221,15,7,...,13,181,0,413,63,0,187,120,149,0
239,01-Jun-20,Deceased,201,0,2,0,0,0,0,0,...,-1,5,0,11,6,0,5,0,8,0
240,02-Jun-20,Confirmed,8812,0,115,2,74,151,4,15,...,41,273,0,1091,99,48,368,84,396,784
241,02-Jun-20,Recovered,4531,0,40,0,53,62,0,9,...,17,222,0,536,35,0,146,30,104,0
242,02-Jun-20,Deceased,222,0,0,0,0,1,1,1,...,2,4,0,13,4,0,7,2,10,0
243,03-Jun-20,Confirmed,9689,0,180,10,271,230,0,64,...,34,279,1,1286,129,151,141,42,340,709
244,03-Jun-20,Recovered,3789,0,50,0,76,222,0,40,...,12,309,0,610,30,0,81,7,170,0
245,03-Jun-20,Deceased,259,0,4,0,0,1,0,0,...,1,6,0,8,7,0,1,1,10,0
246,04-Jun-20,Confirmed,9847,0,141,5,285,126,1,147,...,39,210,0,1384,127,24,367,68,368,360
247,04-Jun-20,Recovered,4390,0,65,0,46,95,8,36,...,14,360,0,585,31,0,182,38,188,0
248,04-Jun-20,Deceased,274,0,3,0,0,3,0,0,...,0,4,0,15,6,0,15,2,10,0
249,05-Jun-20,Confirmed,9472,0,138,4,128,146,7,90,...,46,222,1,1438,143,48,496,62,427,127
250,05-Jun-20,Recovered,4770,0,36,0,50,113,51,25,...,26,255,0,861,40,0,209,47,144,0
251,05-Jun-20,Deceased,286,0,2,0,0,1,0,0,...,1,5,0,12,8,0,12,1,11,0
252,06-Jun-20,Confirmed,10408,0,210,2,230,233,3,60,...,54,253,4,1458,206,55,370,88,435,582
253,06-Jun-20,Recovered,5433,0,75,0,79,65,0,28,...,23,142,0,633,83,0,260,78,207,0
254,06-Jun-20,Deceased,297,0,0,0,0,0,0,2,...,2,13,0,19,10,0,11,0,17,0
255,07-Jun-20,Confirmed,10882,0,199,3,208,239,2,150,...,93,262,0,1515,154,53,433,52,449,418
256,07-Jun-20,Recovered,5191,0,29,0,48,107,1,7,...,14,253,0,604,32,19,277,106,184,0
257,07-Jun-20,Deceased,261,0,2,0,0,1,0,0,...,1,9,0,18,14,0,7,2,13,0
258,08-Jun-20,Confirmed,8536,0,154,6,154,177,6,124,...,55,277,0,1562,92,38,411,56,426,-773
259,08-Jun-20,Recovered,5171,0,42,0,148,137,11,69,...,22,363,0,528,0,0,159,186,162,0
260,08-Jun-20,Deceased,271,0,0,0,0,1,0,0,...,2,6,0,17,5,0,8,0,9,0
261,09-Jun-20,Confirmed,9981,1,69,0,215,208,6,14,...,56,369,6,1685,178,26,388,126,372,874
262,09-Jun-20,Recovered,5634,0,48,1,312,228,0,12,...,39,211,3,798,0,0,325,41,155,0
263,09-Jun-20,Deceased,272,0,2,0,1,2,0,1,...,2,9,0,18,6,1,18,0,10,0
264,10-Jun-20,Confirmed,11156,1,365,4,235,243,2,51,...,86,355,0,1927,191,31,275,25,343,516
265,10-Jun-20,Recovered,6275,0,110,2,152,164,4,4,...,65,241,0,1008,75,47,302,76,159,0
266,10-Jun-20,Deceased,358,0,1,0,1,1,0,1,...,0,4,0,19,8,0,20,2,17,0
267,11-Jun-20,Confirmed,11135,3,182,6,145,250,4,136,...,82,238,0,1875,209,25,478,93,440,-296
268,11-Jun-20,Recovered,6044,0,99,0,184,152,4,70,...,27,206,0,1372,176,39,321,55,209,0
269,11-Jun-20,Deceased,394,0,2,0,0,0,0,0,...,4,6,0,23,9,0,24,1,10,0
270,12-Jun-20,Confirmed,11306,0,207,19,263,148,13,47,...,99,230,50,1982,164,41,528,69,476,-616
271,12-Jun-20,Recovered,7263,0,123,0,152,230,2,123,...,23,236,0,1342,285,0,317,61,218,0
272,12-Jun-20,Deceased,388,0,0,0,2,1,0,0,...,4,7,0,18,9,0,20,5,9,0
273,13-Jun-20,Confirmed,12039,0,222,5,207,193,5,105,...,77,333,0,1989,253,83,502,61,454,-331
274,13-Jun-20,Recovered,8092,0,94,2,221,370,0,87,...,45,326,2,1362,74,37,266,130,336,0
275,13-Jun-20,Deceased,309,0,2,0,0,0,0,0,...,2,10,0,30,8,0,20,2,12,0
276,14-Jun-20,Confirmed,11405,2,294,3,218,186,2,121,...,77,293,5,1974,237,33,497,34,389,-548
277,14-Jun-20,Recovered,7358,0,131,1,155,289,0,88,...,29,229,0,1138,25,118,393,34,518,0

            Date                                     State  Confirmed  \
0     2020-01-30                                    Kerala          1
1     2020-01-30                                     India          1
2     2020-02-02                                    Kerala          2
3     2020-02-02                                     India          2
4     2020-02-03                                    Kerala          3
5     2020-02-03                                     India          3
6     2020-02-14                                    Kerala          3
7     2020-02-14                                     India          3
8     2020-03-02                                     Delhi          1
9     2020-03-02                                    Kerala          3
10    2020-03-02                                 Telangana          1
11    2020-03-02                                     India          5
12    2020-03-03                                     Delhi          1
13    2020-03-03                                    Kerala          3
14    2020-03-03                                 Rajasthan          1
15    2020-03-03                                 Telangana          1
16    2020-03-03                                     India          6
17    2020-03-04                                     Delhi          1
18    2020-03-04                                   Haryana         14
19    2020-03-04                                    Kerala          3
20    2020-03-04                                 Rajasthan          2
21    2020-03-04                                 Telangana          1
22    2020-03-04                                     India         28
23    2020-03-04                             Uttar Pradesh          7
24    2020-03-05                                     Delhi          2
25    2020-03-05                                   Haryana         14
26    2020-03-05                                    Kerala          3
27    2020-03-05                                 Rajasthan          2
28    2020-03-05                                 Telangana          1
29    2020-03-05                                     India         30
30    2020-03-05                             Uttar Pradesh          8
31    2020-03-06                                     Delhi          3
32    2020-03-06                                   Haryana         14
33    2020-03-06                                    Kerala          3
34    2020-03-06                                 Rajasthan          2
35    2020-03-06                                 Telangana          1
36    2020-03-06                                     India         31
37    2020-03-06                             Uttar Pradesh          8
38    2020-03-07                                     Delhi          3
39    2020-03-07                                   Haryana         14
40    2020-03-07                                    Kerala          3
41    2020-03-07                                    Ladakh          2
42    2020-03-07                                 Rajasthan          2
43    2020-03-07                                 Telangana          1
44    2020-03-07                                Tamil Nadu          1
45    2020-03-07                                     India         34
46    2020-03-07                             Uttar Pradesh          8
47    2020-03-08                                     Delhi          3
48    2020-03-08                                   Haryana         14
49    2020-03-08                                    Kerala          8
50    2020-03-08                                    Ladakh          2
51    2020-03-08                                 Rajasthan          2
52    2020-03-08                                 Telangana          1
53    2020-03-08                                Tamil Nadu          1
54    2020-03-08                                     India         39
55    2020-03-08                             Uttar Pradesh          8
56    2020-03-09                                     Delhi          4
57    2020-03-09                                   Haryana         14
58    2020-03-09                         Jammu and Kashmir          1
59    2020-03-09                                 Karnataka          1
60    2020-03-09                                    Kerala          9
61    2020-03-09                                    Ladakh          2
62    2020-03-09                               Maharashtra          2
63    2020-03-09                                    Punjab          1
64    2020-03-09                                 Rajasthan          2
65    2020-03-09                                 Telangana          1
66    2020-03-09                                Tamil Nadu          1
67    2020-03-09                                     India         48
68    2020-03-09                             Uttar Pradesh         10
69    2020-03-10                                     Delhi          4
70    2020-03-10                                   Haryana         14
71    2020-03-10                         Jammu and Kashmir          1
72    2020-03-10                                 Karnataka          4
73    2020-03-10                                    Kerala         17
74    2020-03-10                                    Ladakh          2
75    2020-03-10                               Maharashtra          5
76    2020-03-10                                    Punjab          1
77    2020-03-10                                 Rajasthan          3
78    2020-03-10                                 Telangana          1
79    2020-03-10                                Tamil Nadu          1
80    2020-03-10                                     India         63
81    2020-03-10                             Uttar Pradesh         10
82    2020-03-11                                     Delhi          5
83    2020-03-11                                   Haryana         14
84    2020-03-11                         Jammu and Kashmir          1
85    2020-03-11                                 Karnataka          4
86    2020-03-11                                    Kerala         17
87    2020-03-11                                    Ladakh          3
88    2020-03-11                               Maharashtra         11
89    2020-03-11                                    Punjab          1
90    2020-03-11                                 Rajasthan          3
91    2020-03-11                                 Telangana          1
92    2020-03-11                                Tamil Nadu          1
93    2020-03-11                                     India         71
94    2020-03-11                             Uttar Pradesh         10
95    2020-03-12                            Andhra Pradesh          1
96    2020-03-12                                     Delhi          6
97    2020-03-12                                   Haryana         14
98    2020-03-12                         Jammu and Kashmir          1
99    2020-03-12                                 Karnataka          5
100   2020-03-12                                    Kerala         19
101   2020-03-12                                    Ladakh          3
102   2020-03-12                               Maharashtra         14
103   2020-03-12                                    Punjab          1
104   2020-03-12                                 Rajasthan          3
105   2020-03-12                                 Telangana          1
106   2020-03-12                                Tamil Nadu          1
107   2020-03-12                                     India         81
108   2020-03-12                             Uttar Pradesh         12
109   2020-03-13                            Andhra Pradesh          1
110   2020-03-13                                     Delhi          7
111   2020-03-13                                   Haryana         14
112   2020-03-13                         Jammu and Kashmir          2
113   2020-03-13                                 Karnataka          6
114   2020-03-13                                    Kerala         22
115   2020-03-13                                    Ladakh          3
116   2020-03-13                               Maharashtra         17
117   2020-03-13                                    Punjab          1
118   2020-03-13                                 Rajasthan          3
119   2020-03-13                                 Telangana          1
120   2020-03-13                                Tamil Nadu          1
121   2020-03-13                                     India         91
122   2020-03-13                             Uttar Pradesh         13
123   2020-03-14                            Andhra Pradesh          1
124   2020-03-14                                     Delhi          7
125   2020-03-14                          Himachal Pradesh          0
126   2020-03-14                                   Haryana         14
127   2020-03-14                         Jammu and Kashmir          2
128   2020-03-14                                 Karnataka          6
129   2020-03-14                                    Kerala         22
130   2020-03-14                                    Ladakh          3
131   2020-03-14                               Maharashtra         26
132   2020-03-14                                    Punjab          1
133   2020-03-14                                 Rajasthan          4
134   2020-03-14                                 Telangana          2
135   2020-03-14                                Tamil Nadu          1
136   2020-03-14                                     India        102
137   2020-03-14                             Uttar Pradesh         13
138   2020-03-15                            Andhra Pradesh          1
139   2020-03-15                                     Delhi          7
140   2020-03-15                          Himachal Pradesh          0
141   2020-03-15                                   Haryana         14
142   2020-03-15                         Jammu and Kashmir          2
143   2020-03-15                                 Karnataka          6
144   2020-03-15                                    Kerala         24
145   2020-03-15                                    Ladakh          3
146   2020-03-15                               Maharashtra         32
147   2020-03-15                                    Punjab          1
148   2020-03-15                                 Rajasthan          4
149   2020-03-15                                 Telangana          3
150   2020-03-15                                Tamil Nadu          1
151   2020-03-15                                     India        112
152   2020-03-15                             Uttar Pradesh         13
153   2020-03-15                               Uttarakhand          1
154   2020-03-16                            Andhra Pradesh          1
155   2020-03-16                                     Delhi          7
156   2020-03-16                          Himachal Pradesh          0
157   2020-03-16                                   Haryana         14
158   2020-03-16                         Jammu and Kashmir          3
159   2020-03-16                                 Karnataka          7
160   2020-03-16                                    Kerala         27
161   2020-03-16                                    Ladakh          3
162   2020-03-16                               Maharashtra         39
163   2020-03-16                                    Odisha          1
164   2020-03-16                                    Punjab          1
165   2020-03-16                                 Rajasthan          4
166   2020-03-16                                 Telangana          4
167   2020-03-16                                Tamil Nadu          1
168   2020-03-16                                     India        126
169   2020-03-16                             Uttar Pradesh         13
170   2020-03-16                               Uttarakhand          1
171   2020-03-17                            Andhra Pradesh          1
172   2020-03-17                                     Delhi         10
173   2020-03-17                          Himachal Pradesh          0
174   2020-03-17                                   Haryana         15
175   2020-03-17                         Jammu and Kashmir          3
176   2020-03-17                                 Karnataka         11
177   2020-03-17                                    Kerala         27
178   2020-03-17                                    Ladakh          8
179   2020-03-17                               Maharashtra         41
180   2020-03-17                                    Odisha          1
181   2020-03-17                                    Punjab          1
182   2020-03-17                                Puducherry          1
183   2020-03-17                                 Rajasthan          4
184   2020-03-17                                 Telangana          5
185   2020-03-17                                Tamil Nadu          1
186   2020-03-17                                     India        146
187   2020-03-17                             Uttar Pradesh         15
188   2020-03-17                               Uttarakhand          1
189   2020-03-17                               West Bengal          1
190   2020-03-18                            Andhra Pradesh          1
191   2020-03-18                                     Delhi         11
192   2020-03-18                          Himachal Pradesh          0
193   2020-03-18                                   Haryana         17
194   2020-03-18                         Jammu and Kashmir          4
195   2020-03-18                                 Karnataka         14
196   2020-03-18                                    Kerala         27
197   2020-03-18                                    Ladakh          8
198   2020-03-18                               Maharashtra         45
199   2020-03-18                                    Odisha          1
200   2020-03-18                                    Punjab          1
201   2020-03-18                                Puducherry          1
202   2020-03-18                                 Rajasthan          7
203   2020-03-18                                 Telangana         13
204   2020-03-18                                Tamil Nadu          2
205   2020-03-18                                     India        171
206   2020-03-18                             Uttar Pradesh         17
207   2020-03-18                               Uttarakhand          1
208   2020-03-18                               West Bengal          1
209   2020-03-19                            Andhra Pradesh          3
210   2020-03-19                                Chandigarh          1
211   2020-03-19                              Chhattisgarh          1
212   2020-03-19                                     Delhi         14
213   2020-03-19                                   Gujarat          2
214   2020-03-19                          Himachal Pradesh          0
215   2020-03-19                                   Haryana         17
216   2020-03-19                         Jammu and Kashmir          4
217   2020-03-19                                 Karnataka         15
218   2020-03-19                                    Kerala         28
219   2020-03-19                                    Ladakh          8
220   2020-03-19                               Maharashtra         48
221   2020-03-19                                    Odisha          2
222   2020-03-19                                    Punjab          2
223   2020-03-19                                Puducherry          1
224   2020-03-19                                 Rajasthan          9
225   2020-03-19                                 Telangana         16
226   2020-03-19                                Tamil Nadu          3
227   2020-03-19                                     India        198
228   2020-03-19                             Uttar Pradesh         20
229   2020-03-19                               Uttarakhand          3
230   2020-03-19                               West Bengal          1
231   2020-03-20                            Andhra Pradesh          3
232   2020-03-20                                Chandigarh          5
233   2020-03-20                              Chhattisgarh          1
234   2020-03-20                                     Delhi         20
235   2020-03-20                                   Gujarat          7
236   2020-03-20                          Himachal Pradesh          2
237   2020-03-20                                   Haryana         19
238   2020-03-20                         Jammu and Kashmir          4
239   2020-03-20                                 Karnataka         15
240   2020-03-20                                    Kerala         40
241   2020-03-20                                    Ladakh         10
242   2020-03-20                               Maharashtra         52
243   2020-03-20                            Madhya Pradesh          4
244   2020-03-20                                    Odisha          2
245   2020-03-20                                    Punjab          3
246   2020-03-20                                Puducherry          1
247   2020-03-20                                 Rajasthan         17
248   2020-03-20                                 Telangana         19
249   2020-03-20                                Tamil Nadu          3
250   2020-03-20                                     India        256
251   2020-03-20                             Uttar Pradesh         24
252   2020-03-20                               Uttarakhand          3
253   2020-03-20                               West Bengal          2
254   2020-03-21                            Andhra Pradesh          5
255   2020-03-21                                Chandigarh          5
256   2020-03-21                              Chhattisgarh          1
257   2020-03-21                                     Delhi         27
258   2020-03-21                                   Gujarat         14
259   2020-03-21                          Himachal Pradesh          2
260   2020-03-21                                   Haryana         21
261   2020-03-21                         Jammu and Kashmir          4
262   2020-03-21                                 Karnataka         20
263   2020-03-21                                    Kerala         52
264   2020-03-21                                    Ladakh         13
265   2020-03-21                               Maharashtra         64
266   2020-03-21                            Madhya Pradesh          4
267   2020-03-21                                    Odisha          2
268   2020-03-21                                    Punjab         13
269   2020-03-21                                Puducherry          1
270   2020-03-21                                 Rajasthan         24
271   2020-03-21                                 Telangana         21
272   2020-03-21                                Tamil Nadu          6
273   2020-03-21                                     India        334
274   2020-03-21                             Uttar Pradesh         28
275   2020-03-21                               Uttarakhand          3
276   2020-03-21                               West Bengal          4
277   2020-03-22                            Andhra Pradesh          6
278   2020-03-22                                     Bihar          2
279   2020-03-22                                Chandigarh          6
280   2020-03-22                              Chhattisgarh          1
281   2020-03-22                                     Delhi         28
282   2020-03-22                                   Gujarat         18
283   2020-03-22                          Himachal Pradesh          2

Age_Bracket    28-35
Age_Bracket    28-35
Age_Bracket    28-35
Age_Bracket    28-35
Age_Bracket    1.5
Age_Bracket    0.4
Age_Bracket    0.3
Age_Bracket    1.5
Age_Bracket    2.5
Age_Bracket    0.2
Age_Bracket    0.2
Age_Bracket    0.7
Age_Bracket    0.3
Age_Bracket    29.6
Age_Bracket    0.1
Age_Bracket    0.1
Age_Bracket    3.5
Age_Bracket    0.1
Age_Bracket    2.5
Age_Bracket    3.5
Age_Bracket    0.5
Age_Bracket    0.2
Age_Bracket    2.5
Age_Bracket    0.9
Age_Bracket    1.5
Age_Bracket    1.5
Age_Bracket    1.5
Age_Bracket    0.5
Age_Bracket    0.25
Age_Bracket    0.1
Age_Bracket    0.1
Age_Bracket    1.5
Age_Bracket    0.9
Age_Bracket    0.1
Age_Bracket    0.1
Age_Bracket    2.5
Age_Bracket    3.5
Age_Bracket    1.5
Age_Bracket    0.7
Age_Bracket    0.1
Age_Bracket    0.5
Age_Bracket    0.1
Age_Bracket    0.1
Age_Bracket    1.5
Age_Bracket    2.5
Age_Bracket    0.1
Age_Bracket    54.9
Age_Bracket    0.7
Age_Bracket    0.1
Age_Bracket    0.1
Age_Bracket    0.6
Age_Bracket    0.3
Age_Bracket    0.67
Age_Bracket    0.5
Age_Bracket    1.5
Age_Bracket    0.33
Age_Bracket    0.5
Age_Bracket    0.3
Age_Bracket    0.67
Age_Bracket    0.6
Age_Bracket    0.4
Age_Bracket    1.6
Age_Bracket    0.4
Age_Bracket    0.7
Age_Bracket    0.7
Age_Bracket    0.6
Age_Bracket    0.75
Age_Bracket    0.7
Age_Bracket    2.5
Age_Bracket    0.75
Age_Bracket    18-28
Age_Bracket    18-28
Age_Bracket    0.9
Age_Bracket    0.1
Age_Bracket    0.2
Age_Bracket    0.3
Age_Bracket    0.3
Age_Bracket    9.5
Age_Bracket    0.6
Age_Bracket    0.1
Age_Bracket    1.5
Age_Bracket    0.1
Age_Bracket    0.9
Age_Bracket    0.6
Age_Bracket    0.1
Age_Bracket    0.9
Age_Bracket    0.9
Age_Bracket    100
Age_Bracket    0.7
Age_Bracket    0.6
Age_Bracket    0.01
Age_Bracket    0.1
Age_Bracket    0.1
Age_Bracket    0.1
Age_Bracket    0.1
Age_Bracket    0.9
Age_Bracket    1.5
Age_Bracket    0.7
Age_Bracket    2.5
Age_Bracket    1.5
Age_Bracket    0.9
Age_Bracket    100
Age_Bracket    0.8
Age_Bracket    0.1
Age_Bracket    1.5
Age_Bracket    0.1
Age_Bracket    0.1
Age_Bracket    105
Age_Bracket    2.4
Age_Bracket    4.5
Age_Bracket    2.5
Age_Bracket    1.5
Age_Bracket    0.05
Age_Bracket    0.5
Age_Bracket    102
Age_Bracket    0.1
Age_Bracket    0.04
Age_Bracket    0.1
Age_Bracket    0.6
Age_Bracket    0.3
Age_Bracket    0.2
Age_Bracket    0.1
Age_Bracket    0.04
Age_Bracket    0.01
Age_Bracket    0.1
Age_Bracket    1.9
Age_Bracket    101
Age_Bracket    1.6
Age_Bracket    103

,Date_Announced,Current_Status,Detected_District,Detected_State,Age_Bracket,Patient_id,Age_0_15,Age_15_30,Age_30_45,Age_45_60,Age_60
0,30/01/2020,Recovered,thrissur,kerala,20,0,0,1,0,0,0
3,02/03/2020,Recovered,east delhi,delhi,45,1,0,0,1,0,0
4,02/03/2020,Recovered,hyderabad,telangana,24,2,0,1,0,0,0
5,03/03/2020,Recovered,italians,rajasthan,69,3,0,0,0,0,1
6,04/03/2020,Recovered,italians,haryana,55,4,0,0,0,1,0
...,...,...,...,...,...,...,...,...,...,...,...
427574,28/11/2020,Deceased,imphal west,manipur,62,116642,0,0,0,0,1
427575,28/11/2020,Deceased,imphal west,manipur,69,116643,0,0,0,0,1
427576,28/11/2020,Deceased,imphal west,manipur,62,116644,0,0,0,0,1
427577,28/11/2020,Deceased,imphal east,manipur,80,116645,0,0,0,0,1
427578,28/11/2020,Deceased,thoubal,manipur,88,116646,0,0,0,0,1

In [113]:
for i in test_data.index:
    age = (test_data.loc[i,['Age_Bracket']])
    x = age.to_string()
    if len(x) >= 18:
        age = x.split('-')[0][-2:]
    age = int(age)
    if age > 0 and age <= 15:
        test_data.loc[i,['Age_0_15']] = 1
    elif age > 15 and age <= 30:
        test_data.loc[i,['Age_15_30']] = 1
    elif age > 30 and age <= 45:
        test_data.loc[i,['Age_30_45']] = 1
    elif age > 45 and age <= 60:
        test_data.loc[i,['Age_45_60']] = 1
    else:
        test_data.loc[i,['Age_60']] = 1
test_data

NameError: name 'ceil' is not defined

In [9]:
test_data = data.loc[1:50]

In [13]:
test_data

,Date_Announced,Current_Status,Detected_District,Detected_State,Age_Bracket,Patient_id,Age_0_15,Age_15_30,Age_30_45,Age_45_60,Age_60
3,02/03/2020,Recovered,east delhi,delhi,45,1,0,0,0,0,0
4,02/03/2020,Recovered,hyderabad,telangana,24,2,0,0,0,0,0
5,03/03/2020,Recovered,italians,rajasthan,69,3,0,0,0,0,0
6,04/03/2020,Recovered,italians,haryana,55,4,0,0,0,0,0
7,04/03/2020,Recovered,italians,haryana,55,5,0,0,0,0,0
8,04/03/2020,Recovered,italians,haryana,55,6,0,0,0,0,0
9,04/03/2020,Recovered,italians,haryana,55,7,0,0,0,0,0
10,04/03/2020,Recovered,italians,haryana,55,8,0,0,0,0,0
11,04/03/2020,Recovered,italians,haryana,55,9,0,0,0,0,0
12,04/03/2020,Recovered,italians,haryana,55,10,0,0,0,0,0
13,04/03/2020,Recovered,italians,haryana,55,11,0,0,0,0,0
14,04/03/2020,Recovered,italians,haryana,55,12,0,0,0,0,0
15,04/03/2020,Recovered,italians,haryana,55,13,0,0,0,0,0
16,04/03/2020,Recovered,italians,haryana,55,14,0,0,0,0,0
17,04/03/2020,Recovered,italians,haryana,55,15,0,0,0,0,0
18,04/03/2020,Hospitalized,italians,haryana,55,16,0,0,0,0,0
19,04/03/2020,Hospitalized,italians,haryana,55,17,0,0,0,0,0
20,04/03/2020,Recovered,italians,rajasthan,70,18,0,0,0,0,0
23,04/03/2020,Recovered,agra,uttar pradesh,45,19,0,0,0,0,0
25,04/03/2020,Recovered,agra,uttar pradesh,16,20,0,0,0,0,0
28,05/03/2020,Hospitalized,south west delhi,delhi,27,21,0,0,0,0,0
29,05/03/2020,Recovered,ghaziabad,uttar pradesh,59,22,0,0,0,0,0
31,07/03/2020,Hospitalized,leh,ladakh,65,23,0,0,0,0,0
32,07/03/2020,Hospitalized,leh,ladakh,75,24,0,0,0,0,0
33,07/03/2020,Recovered,kancheepuram,tamil nadu,45,25,0,0,0,0,0
34,08/03/2020,Recovered,pathanamthitta,kerala,24,26,0,0,0,0,0
35,08/03/2020,Recovered,pathanamthitta,kerala,54,27,0,0,0,0,0
36,08/03/2020,Recovered,pathanamthitta,kerala,53,28,0,0,0,0,0
37,08/03/2020,Recovered,pathanamthitta,kerala,65,29,0,0,0,0,0
38,08/03/2020,Recovered,pathanamthitta,kerala,61,30,0,0,0,0,0
39,09/03/2020,Hospitalized,north delhi,delhi,25,31,0,0,0,0,0
40,09/03/2020,Hospitalized,jammu,jammu and kashmir,63,32,0,0,0,0,0
41,09/03/2020,Recovered,bengaluru urban,karnataka,46,33,0,0,0,0,0
42,09/03/2020,Recovered,kannur,kerala,3,34,0,0,0,0,0
46,09/03/2020,Recovered,agra,uttar pradesh,48,35,0,0,0,0,0
50,10/03/2020,Recovered,bengaluru urban,karnataka,40,36,0,0,0,0,0

In [14]:
test_data.loc[20,['Age_Bracket']] = '20-30'

/home/hoozeeloogaan/Programs/anaconda3/lib/python3.7/site-packages/pandas/core/indexing.py:494: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  self.obj[item] = s

In [99]:
test_data = data.loc[1:50]

TypeError: '>' not supported between instances of 'str' and 'int'

In [12]:
newlist = [0]*len(test_data)
test_data['Age_0_15'] = newlist
test_data['Age_15_30'] = newlist
test_data['Age_30_45'] = newlist
test_data['Age_45_60'] = newlist
test_data['Age_60'] = newlist

/home/hoozeeloogaan/Programs/anaconda3/lib/python3.7/site-packages/ipykernel_launcher.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

/home/hoozeeloogaan/Programs/anaconda3/lib/python3.7/site-packages/ipykernel_launcher.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  This is separate from the ipykernel package so we can avoid doing imports until
/home/hoozeeloogaan/Programs/anaconda3/lib/python3.7/site-packages/ipykernel_launcher.py:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  after removing the cwd from sys.path.
/home/hoozeeloogaan/Programs/anaconda3/lib/python3.7/site-packages/ipykernel_launcher.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  """
/home/hoozeeloogaan/Programs/anaconda3/lib/python3.7/site-packages/ipykernel_launcher.py:6: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

In [ ]:
for i in a:
    b.append(str(a))

In [24]:
b = "10"
print(b.isnumeric())
print(type(b))

True
<class 'str'>

In [102]:
data

,Date_Announced,Current_Status,Detected_District,Detected_State,Age_Bracket,Patient_id,Age_0_15,Age_15_30,Age_30_45,Age_45_60,Age_60
0,30/01/2020,Recovered,thrissur,kerala,20,0,0,1,0,0,0
3,02/03/2020,Recovered,east delhi,delhi,45,1,0,0,1,0,0
4,02/03/2020,Recovered,hyderabad,telangana,24,2,0,1,0,0,0
5,03/03/2020,Recovered,italians,rajasthan,69,3,0,0,0,0,1
6,04/03/2020,Recovered,italians,haryana,55,4,0,0,0,1,0
...,...,...,...,...,...,...,...,...,...,...,...
427574,28/11/2020,Deceased,imphal west,manipur,62,116643,0,0,0,0,0
427575,28/11/2020,Deceased,imphal west,manipur,69,116644,0,0,0,0,0
427576,28/11/2020,Deceased,imphal west,manipur,62,116645,0,0,0,0,0
427577,28/11/2020,Deceased,imphal east,manipur,80,116646,0,0,0,0,0
427578,28/11/2020,Deceased,thoubal,manipur,88,116647,0,0,0,0,0

In [112]:
x = '.5'
float(x)

0.5

In [10]:
df[df['Age Bracket'] == 's']

,Age Bracket,Backup Notes,Contracted from which Patient (Suspected),Current Status,Date Announced,Detected City,Detected District,Detected State,Entry_ID,Estimated Onset Date,...,Patient Number,Source_1,Source_2,Source_3,State Patient Number,State code,Status Change Date,Type of transmission,filename,months
240223,s,NaN,NaN,Deceased,02/08/2020,NaN,Srikakulam,Andhra Pradesh,211982.0,NaN,...,NaN,https://twitter.com/ArogyaAndhra/status/128991...,NaN,NaN,NaN,AP,NaN,NaN,Dataset/raw_data12.csv,NaN